// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	"github.com/jailtonjunior94/financial/internal/transaction/domain/interfaces"
	vos0 "github.com/jailtonjunior94/financial/pkg/domain/vos"
	mock "github.com/stretchr/testify/mock"
)

// NewInvoiceProvider creates a new instance of InvoiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvoiceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvoiceProvider {
	mock := &InvoiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InvoiceProvider is an autogenerated mock type for the InvoiceProvider type
type InvoiceProvider struct {
	mock.Mock
}

type InvoiceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *InvoiceProvider) EXPECT() *InvoiceProvider_Expecter {
	return &InvoiceProvider_Expecter{mock: &_m.Mock}
}

// FindOrCreate provides a mock function for the type InvoiceProvider
func (_mock *InvoiceProvider) FindOrCreate(ctx context.Context, userID vos.UUID, cardID vos.UUID, referenceMonth vos0.ReferenceMonth, dueDate time.Time) (*interfaces.InvoiceInfo, error) {
	ret := _mock.Called(ctx, userID, cardID, referenceMonth, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 *interfaces.InvoiceInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID, vos0.ReferenceMonth, time.Time) (*interfaces.InvoiceInfo, error)); ok {
		return returnFunc(ctx, userID, cardID, referenceMonth, dueDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID, vos0.ReferenceMonth, time.Time) *interfaces.InvoiceInfo); ok {
		r0 = returnFunc(ctx, userID, cardID, referenceMonth, dueDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.InvoiceInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, vos.UUID, vos0.ReferenceMonth, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, cardID, referenceMonth, dueDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceProvider_FindOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreate'
type InvoiceProvider_FindOrCreate_Call struct {
	*mock.Call
}

// FindOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
//   - cardID vos.UUID
//   - referenceMonth vos0.ReferenceMonth
//   - dueDate time.Time
func (_e *InvoiceProvider_Expecter) FindOrCreate(ctx interface{}, userID interface{}, cardID interface{}, referenceMonth interface{}, dueDate interface{}) *InvoiceProvider_FindOrCreate_Call {
	return &InvoiceProvider_FindOrCreate_Call{Call: _e.mock.On("FindOrCreate", ctx, userID, cardID, referenceMonth, dueDate)}
}

func (_c *InvoiceProvider_FindOrCreate_Call) Run(run func(ctx context.Context, userID vos.UUID, cardID vos.UUID, referenceMonth vos0.ReferenceMonth, dueDate time.Time)) *InvoiceProvider_FindOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		var arg2 vos.UUID
		if args[2] != nil {
			arg2 = args[2].(vos.UUID)
		}
		var arg3 vos0.ReferenceMonth
		if args[3] != nil {
			arg3 = args[3].(vos0.ReferenceMonth)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *InvoiceProvider_FindOrCreate_Call) Return(invoiceInfo *interfaces.InvoiceInfo, err error) *InvoiceProvider_FindOrCreate_Call {
	_c.Call.Return(invoiceInfo, err)
	return _c
}

func (_c *InvoiceProvider_FindOrCreate_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, cardID vos.UUID, referenceMonth vos0.ReferenceMonth, dueDate time.Time) (*interfaces.InvoiceInfo, error)) *InvoiceProvider_FindOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type InvoiceProvider
func (_mock *InvoiceProvider) GetStatus(ctx context.Context, invoiceID vos.UUID) (string, error) {
	ret := _mock.Called(ctx, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) (string, error)); ok {
		return returnFunc(ctx, invoiceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) string); ok {
		r0 = returnFunc(ctx, invoiceID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID) error); ok {
		r1 = returnFunc(ctx, invoiceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceProvider_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type InvoiceProvider_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID vos.UUID
func (_e *InvoiceProvider_Expecter) GetStatus(ctx interface{}, invoiceID interface{}) *InvoiceProvider_GetStatus_Call {
	return &InvoiceProvider_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, invoiceID)}
}

func (_c *InvoiceProvider_GetStatus_Call) Run(run func(ctx context.Context, invoiceID vos.UUID)) *InvoiceProvider_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceProvider_GetStatus_Call) Return(s string, err error) *InvoiceProvider_GetStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *InvoiceProvider_GetStatus_Call) RunAndReturn(run func(ctx context.Context, invoiceID vos.UUID) (string, error)) *InvoiceProvider_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}
