// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/database"
	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	"github.com/jailtonjunior94/financial/internal/transaction/domain/entities"
	"github.com/jailtonjunior94/financial/internal/transaction/domain/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

type TransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepository) EXPECT() *TransactionRepository_Expecter {
	return &TransactionRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) FindByID(ctx context.Context, id vos.UUID) (*entities.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) (*entities.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) *entities.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type TransactionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id vos.UUID
func (_e *TransactionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *TransactionRepository_FindByID_Call {
	return &TransactionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *TransactionRepository_FindByID_Call) Run(run func(ctx context.Context, id vos.UUID)) *TransactionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionRepository_FindByID_Call) Return(transaction *entities.Transaction, err error) *TransactionRepository_FindByID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *TransactionRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id vos.UUID) (*entities.Transaction, error)) *TransactionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByInstallmentGroup provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) FindByInstallmentGroup(ctx context.Context, groupID vos.UUID) ([]*entities.Transaction, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for FindByInstallmentGroup")
	}

	var r0 []*entities.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) ([]*entities.Transaction, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) []*entities.Transaction); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionRepository_FindByInstallmentGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByInstallmentGroup'
type TransactionRepository_FindByInstallmentGroup_Call struct {
	*mock.Call
}

// FindByInstallmentGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID vos.UUID
func (_e *TransactionRepository_Expecter) FindByInstallmentGroup(ctx interface{}, groupID interface{}) *TransactionRepository_FindByInstallmentGroup_Call {
	return &TransactionRepository_FindByInstallmentGroup_Call{Call: _e.mock.On("FindByInstallmentGroup", ctx, groupID)}
}

func (_c *TransactionRepository_FindByInstallmentGroup_Call) Run(run func(ctx context.Context, groupID vos.UUID)) *TransactionRepository_FindByInstallmentGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionRepository_FindByInstallmentGroup_Call) Return(transactions []*entities.Transaction, err error) *TransactionRepository_FindByInstallmentGroup_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *TransactionRepository_FindByInstallmentGroup_Call) RunAndReturn(run func(ctx context.Context, groupID vos.UUID) ([]*entities.Transaction, error)) *TransactionRepository_FindByInstallmentGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaginated provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) ListPaginated(ctx context.Context, params interfaces.ListParams) ([]*entities.Transaction, string, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPaginated")
	}

	var r0 []*entities.Transaction
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListParams) ([]*entities.Transaction, string, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListParams) []*entities.Transaction); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.ListParams) string); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, interfaces.ListParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TransactionRepository_ListPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaginated'
type TransactionRepository_ListPaginated_Call struct {
	*mock.Call
}

// ListPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - params interfaces.ListParams
func (_e *TransactionRepository_Expecter) ListPaginated(ctx interface{}, params interface{}) *TransactionRepository_ListPaginated_Call {
	return &TransactionRepository_ListPaginated_Call{Call: _e.mock.On("ListPaginated", ctx, params)}
}

func (_c *TransactionRepository_ListPaginated_Call) Run(run func(ctx context.Context, params interfaces.ListParams)) *TransactionRepository_ListPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.ListParams
		if args[1] != nil {
			arg1 = args[1].(interfaces.ListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionRepository_ListPaginated_Call) Return(transactions []*entities.Transaction, s string, err error) *TransactionRepository_ListPaginated_Call {
	_c.Call.Return(transactions, s, err)
	return _c
}

func (_c *TransactionRepository_ListPaginated_Call) RunAndReturn(run func(ctx context.Context, params interfaces.ListParams) ([]*entities.Transaction, string, error)) *TransactionRepository_ListPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) Save(ctx context.Context, tx database.DBTX, t *entities.Transaction) error {
	ret := _mock.Called(ctx, tx, t)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, *entities.Transaction) error); ok {
		r0 = returnFunc(ctx, tx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type TransactionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - tx database.DBTX
//   - t *entities.Transaction
func (_e *TransactionRepository_Expecter) Save(ctx interface{}, tx interface{}, t interface{}) *TransactionRepository_Save_Call {
	return &TransactionRepository_Save_Call{Call: _e.mock.On("Save", ctx, tx, t)}
}

func (_c *TransactionRepository_Save_Call) Run(run func(ctx context.Context, tx database.DBTX, t *entities.Transaction)) *TransactionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 *entities.Transaction
		if args[2] != nil {
			arg2 = args[2].(*entities.Transaction)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionRepository_Save_Call) Return(err error) *TransactionRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionRepository_Save_Call) RunAndReturn(run func(ctx context.Context, tx database.DBTX, t *entities.Transaction) error) *TransactionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAll provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) SaveAll(ctx context.Context, tx database.DBTX, ts []*entities.Transaction) error {
	ret := _mock.Called(ctx, tx, ts)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, []*entities.Transaction) error); ok {
		r0 = returnFunc(ctx, tx, ts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionRepository_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type TransactionRepository_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - ctx context.Context
//   - tx database.DBTX
//   - ts []*entities.Transaction
func (_e *TransactionRepository_Expecter) SaveAll(ctx interface{}, tx interface{}, ts interface{}) *TransactionRepository_SaveAll_Call {
	return &TransactionRepository_SaveAll_Call{Call: _e.mock.On("SaveAll", ctx, tx, ts)}
}

func (_c *TransactionRepository_SaveAll_Call) Run(run func(ctx context.Context, tx database.DBTX, ts []*entities.Transaction)) *TransactionRepository_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 []*entities.Transaction
		if args[2] != nil {
			arg2 = args[2].([]*entities.Transaction)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionRepository_SaveAll_Call) Return(err error) *TransactionRepository_SaveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionRepository_SaveAll_Call) RunAndReturn(run func(ctx context.Context, tx database.DBTX, ts []*entities.Transaction) error) *TransactionRepository_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) Update(ctx context.Context, tx database.DBTX, t *entities.Transaction) error {
	ret := _mock.Called(ctx, tx, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, *entities.Transaction) error); ok {
		r0 = returnFunc(ctx, tx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TransactionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tx database.DBTX
//   - t *entities.Transaction
func (_e *TransactionRepository_Expecter) Update(ctx interface{}, tx interface{}, t interface{}) *TransactionRepository_Update_Call {
	return &TransactionRepository_Update_Call{Call: _e.mock.On("Update", ctx, tx, t)}
}

func (_c *TransactionRepository_Update_Call) Run(run func(ctx context.Context, tx database.DBTX, t *entities.Transaction)) *TransactionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 *entities.Transaction
		if args[2] != nil {
			arg2 = args[2].(*entities.Transaction)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionRepository_Update_Call) Return(err error) *TransactionRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionRepository_Update_Call) RunAndReturn(run func(ctx context.Context, tx database.DBTX, t *entities.Transaction) error) *TransactionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAll provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) UpdateAll(ctx context.Context, tx database.DBTX, ts []*entities.Transaction) error {
	ret := _mock.Called(ctx, tx, ts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, []*entities.Transaction) error); ok {
		r0 = returnFunc(ctx, tx, ts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionRepository_UpdateAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAll'
type TransactionRepository_UpdateAll_Call struct {
	*mock.Call
}

// UpdateAll is a helper method to define mock.On call
//   - ctx context.Context
//   - tx database.DBTX
//   - ts []*entities.Transaction
func (_e *TransactionRepository_Expecter) UpdateAll(ctx interface{}, tx interface{}, ts interface{}) *TransactionRepository_UpdateAll_Call {
	return &TransactionRepository_UpdateAll_Call{Call: _e.mock.On("UpdateAll", ctx, tx, ts)}
}

func (_c *TransactionRepository_UpdateAll_Call) Run(run func(ctx context.Context, tx database.DBTX, ts []*entities.Transaction)) *TransactionRepository_UpdateAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 []*entities.Transaction
		if args[2] != nil {
			arg2 = args[2].([]*entities.Transaction)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionRepository_UpdateAll_Call) Return(err error) *TransactionRepository_UpdateAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionRepository_UpdateAll_Call) RunAndReturn(run func(ctx context.Context, tx database.DBTX, ts []*entities.Transaction) error) *TransactionRepository_UpdateAll_Call {
	_c.Call.Return(run)
	return _c
}
