// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jailtonjunior94/financial/pkg/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenValidator creates a new instance of TokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenValidator {
	mock := &TokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenValidator is an autogenerated mock type for the TokenValidator type
type TokenValidator struct {
	mock.Mock
}

type TokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenValidator) EXPECT() *TokenValidator_Expecter {
	return &TokenValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type TokenValidator
func (_mock *TokenValidator) Validate(ctx context.Context, token string) (*auth.AuthenticatedUser, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *auth.AuthenticatedUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auth.AuthenticatedUser, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auth.AuthenticatedUser); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthenticatedUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type TokenValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenValidator_Expecter) Validate(ctx interface{}, token interface{}) *TokenValidator_Validate_Call {
	return &TokenValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, token)}
}

func (_c *TokenValidator_Validate_Call) Run(run func(ctx context.Context, token string)) *TokenValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenValidator_Validate_Call) Return(authenticatedUser *auth.AuthenticatedUser, err error) *TokenValidator_Validate_Call {
	_c.Call.Return(authenticatedUser, err)
	return _c
}

func (_c *TokenValidator_Validate_Call) RunAndReturn(run func(ctx context.Context, token string) (*auth.AuthenticatedUser, error)) *TokenValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
