// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	"github.com/jailtonjunior94/financial/internal/budget/domain/entities"
	"github.com/jailtonjunior94/financial/internal/budget/domain/interfaces"
	pkgVos "github.com/jailtonjunior94/financial/pkg/domain/vos"
	mock "github.com/stretchr/testify/mock"
)

// NewBudgetRepository creates a new instance of BudgetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBudgetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BudgetRepository {
	mock := &BudgetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BudgetRepository is an autogenerated mock type for the BudgetRepository type
type BudgetRepository struct {
	mock.Mock
}

type BudgetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BudgetRepository) EXPECT() *BudgetRepository_Expecter {
	return &BudgetRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type BudgetRepository
func (_mock *BudgetRepository) Delete(ctx context.Context, id vos.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) error); ok {
		return returnFunc(ctx, id)
	}
	return ret.Error(0)
}

// BudgetRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BudgetRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id vos.UUID
func (_e *BudgetRepository_Expecter) Delete(ctx interface{}, id interface{}) *BudgetRepository_Delete_Call {
	return &BudgetRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *BudgetRepository_Delete_Call) Run(run func(ctx context.Context, id vos.UUID)) *BudgetRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *BudgetRepository_Delete_Call) Return(err error) *BudgetRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BudgetRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id vos.UUID) error) *BudgetRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type BudgetRepository
func (_mock *BudgetRepository) FindByID(ctx context.Context, userID vos.UUID, id vos.UUID) (*entities.Budget, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Budget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID) (*entities.Budget, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID) *entities.Budget); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Budget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, vos.UUID) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BudgetRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type BudgetRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
//   - id vos.UUID
func (_e *BudgetRepository_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *BudgetRepository_FindByID_Call {
	return &BudgetRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *BudgetRepository_FindByID_Call) Run(run func(ctx context.Context, userID vos.UUID, id vos.UUID)) *BudgetRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		var arg2 vos.UUID
		if args[2] != nil {
			arg2 = args[2].(vos.UUID)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *BudgetRepository_FindByID_Call) Return(budget *entities.Budget, err error) *BudgetRepository_FindByID_Call {
	_c.Call.Return(budget, err)
	return _c
}

func (_c *BudgetRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, id vos.UUID) (*entities.Budget, error)) *BudgetRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserIDAndReferenceMonth provides a mock function for the type BudgetRepository
func (_mock *BudgetRepository) FindByUserIDAndReferenceMonth(ctx context.Context, userID vos.UUID, referenceMonth pkgVos.ReferenceMonth) (*entities.Budget, error) {
	ret := _mock.Called(ctx, userID, referenceMonth)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserIDAndReferenceMonth")
	}

	var r0 *entities.Budget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, pkgVos.ReferenceMonth) (*entities.Budget, error)); ok {
		return returnFunc(ctx, userID, referenceMonth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, pkgVos.ReferenceMonth) *entities.Budget); ok {
		r0 = returnFunc(ctx, userID, referenceMonth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Budget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, pkgVos.ReferenceMonth) error); ok {
		r1 = returnFunc(ctx, userID, referenceMonth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BudgetRepository_FindByUserIDAndReferenceMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserIDAndReferenceMonth'
type BudgetRepository_FindByUserIDAndReferenceMonth_Call struct {
	*mock.Call
}

// FindByUserIDAndReferenceMonth is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
//   - referenceMonth pkgVos.ReferenceMonth
func (_e *BudgetRepository_Expecter) FindByUserIDAndReferenceMonth(ctx interface{}, userID interface{}, referenceMonth interface{}) *BudgetRepository_FindByUserIDAndReferenceMonth_Call {
	return &BudgetRepository_FindByUserIDAndReferenceMonth_Call{Call: _e.mock.On("FindByUserIDAndReferenceMonth", ctx, userID, referenceMonth)}
}

func (_c *BudgetRepository_FindByUserIDAndReferenceMonth_Call) Run(run func(ctx context.Context, userID vos.UUID, referenceMonth pkgVos.ReferenceMonth)) *BudgetRepository_FindByUserIDAndReferenceMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		var arg2 pkgVos.ReferenceMonth
		if args[2] != nil {
			arg2 = args[2].(pkgVos.ReferenceMonth)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *BudgetRepository_FindByUserIDAndReferenceMonth_Call) Return(budget *entities.Budget, err error) *BudgetRepository_FindByUserIDAndReferenceMonth_Call {
	_c.Call.Return(budget, err)
	return _c
}

func (_c *BudgetRepository_FindByUserIDAndReferenceMonth_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, referenceMonth pkgVos.ReferenceMonth) (*entities.Budget, error)) *BudgetRepository_FindByUserIDAndReferenceMonth_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type BudgetRepository
func (_mock *BudgetRepository) Insert(ctx context.Context, budget *entities.Budget) error {
	ret := _mock.Called(ctx, budget)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Budget) error); ok {
		r0 = returnFunc(ctx, budget)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BudgetRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type BudgetRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - budget *entities.Budget
func (_e *BudgetRepository_Expecter) Insert(ctx interface{}, budget interface{}) *BudgetRepository_Insert_Call {
	return &BudgetRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, budget)}
}

func (_c *BudgetRepository_Insert_Call) Run(run func(ctx context.Context, budget *entities.Budget)) *BudgetRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Budget
		if args[1] != nil {
			arg1 = args[1].(*entities.Budget)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BudgetRepository_Insert_Call) Return(err error) *BudgetRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BudgetRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, budget *entities.Budget) error) *BudgetRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertItems provides a mock function for the type BudgetRepository
func (_mock *BudgetRepository) InsertItems(ctx context.Context, items []*entities.BudgetItem) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for InsertItems")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entities.BudgetItem) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BudgetRepository_InsertItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertItems'
type BudgetRepository_InsertItems_Call struct {
	*mock.Call
}

// InsertItems is a helper method to define mock.On call
//   - ctx context.Context
//   - items []*entities.BudgetItem
func (_e *BudgetRepository_Expecter) InsertItems(ctx interface{}, items interface{}) *BudgetRepository_InsertItems_Call {
	return &BudgetRepository_InsertItems_Call{Call: _e.mock.On("InsertItems", ctx, items)}
}

func (_c *BudgetRepository_InsertItems_Call) Run(run func(ctx context.Context, items []*entities.BudgetItem)) *BudgetRepository_InsertItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entities.BudgetItem
		if args[1] != nil {
			arg1 = args[1].([]*entities.BudgetItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BudgetRepository_InsertItems_Call) Return(err error) *BudgetRepository_InsertItems_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BudgetRepository_InsertItems_Call) RunAndReturn(run func(ctx context.Context, items []*entities.BudgetItem) error) *BudgetRepository_InsertItems_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaginated provides a mock function for the type BudgetRepository
func (_mock *BudgetRepository) ListPaginated(ctx context.Context, params interfaces.ListBudgetsParams) ([]*entities.Budget, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPaginated")
	}

	var r0 []*entities.Budget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListBudgetsParams) ([]*entities.Budget, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListBudgetsParams) []*entities.Budget); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Budget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.ListBudgetsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BudgetRepository_ListPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaginated'
type BudgetRepository_ListPaginated_Call struct {
	*mock.Call
}

// ListPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - params interfaces.ListBudgetsParams
func (_e *BudgetRepository_Expecter) ListPaginated(ctx interface{}, params interface{}) *BudgetRepository_ListPaginated_Call {
	return &BudgetRepository_ListPaginated_Call{Call: _e.mock.On("ListPaginated", ctx, params)}
}

func (_c *BudgetRepository_ListPaginated_Call) Run(run func(ctx context.Context, params interfaces.ListBudgetsParams)) *BudgetRepository_ListPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.ListBudgetsParams
		if args[1] != nil {
			arg1 = args[1].(interfaces.ListBudgetsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BudgetRepository_ListPaginated_Call) Return(budgets []*entities.Budget, err error) *BudgetRepository_ListPaginated_Call {
	_c.Call.Return(budgets, err)
	return _c
}

func (_c *BudgetRepository_ListPaginated_Call) RunAndReturn(run func(ctx context.Context, params interfaces.ListBudgetsParams) ([]*entities.Budget, error)) *BudgetRepository_ListPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type BudgetRepository
func (_mock *BudgetRepository) Update(ctx context.Context, budget *entities.Budget) error {
	ret := _mock.Called(ctx, budget)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Budget) error); ok {
		r0 = returnFunc(ctx, budget)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BudgetRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type BudgetRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - budget *entities.Budget
func (_e *BudgetRepository_Expecter) Update(ctx interface{}, budget interface{}) *BudgetRepository_Update_Call {
	return &BudgetRepository_Update_Call{Call: _e.mock.On("Update", ctx, budget)}
}

func (_c *BudgetRepository_Update_Call) Run(run func(ctx context.Context, budget *entities.Budget)) *BudgetRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Budget
		if args[1] != nil {
			arg1 = args[1].(*entities.Budget)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BudgetRepository_Update_Call) Return(err error) *BudgetRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BudgetRepository_Update_Call) RunAndReturn(run func(ctx context.Context, budget *entities.Budget) error) *BudgetRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type BudgetRepository
func (_mock *BudgetRepository) UpdateItem(ctx context.Context, item *entities.BudgetItem) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.BudgetItem) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BudgetRepository_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type BudgetRepository_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *entities.BudgetItem
func (_e *BudgetRepository_Expecter) UpdateItem(ctx interface{}, item interface{}) *BudgetRepository_UpdateItem_Call {
	return &BudgetRepository_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, item)}
}

func (_c *BudgetRepository_UpdateItem_Call) Run(run func(ctx context.Context, item *entities.BudgetItem)) *BudgetRepository_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.BudgetItem
		if args[1] != nil {
			arg1 = args[1].(*entities.BudgetItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BudgetRepository_UpdateItem_Call) Return(err error) *BudgetRepository_UpdateItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BudgetRepository_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, item *entities.BudgetItem) error) *BudgetRepository_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
