// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewCategoryProvider creates a new instance of CategoryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryProvider {
	mock := &CategoryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CategoryProvider is an autogenerated mock type for the CategoryProvider type
type CategoryProvider struct {
	mock.Mock
}

type CategoryProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryProvider) EXPECT() *CategoryProvider_Expecter {
	return &CategoryProvider_Expecter{mock: &_m.Mock}
}

// ValidateCategories provides a mock function for the type CategoryProvider
func (_mock *CategoryProvider) ValidateCategories(ctx context.Context, userID string, categoryIDs []string) error {
	ret := _mock.Called(ctx, userID, categoryIDs)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCategories")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, userID, categoryIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type CategoryProvider_ValidateCategories_Call struct {
	*mock.Call
}

func (_e *CategoryProvider_Expecter) ValidateCategories(ctx any, userID any, categoryIDs any) *CategoryProvider_ValidateCategories_Call {
	return &CategoryProvider_ValidateCategories_Call{Call: _e.mock.On("ValidateCategories", ctx, userID, categoryIDs)}
}

func (_c *CategoryProvider_ValidateCategories_Call) Run(run func(ctx context.Context, userID string, categoryIDs []string)) *CategoryProvider_ValidateCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *CategoryProvider_ValidateCategories_Call) Return(err error) *CategoryProvider_ValidateCategories_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CategoryProvider_ValidateCategories_Call) Once() *CategoryProvider_ValidateCategories_Call {
	_c.Call.Once()
	return _c
}

func (_c *CategoryProvider_ValidateCategories_Call) Times(i int) *CategoryProvider_ValidateCategories_Call {
	_c.Call.Times(i)
	return _c
}
