// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	pkgVos "github.com/jailtonjunior94/financial/pkg/domain/vos"
	mock "github.com/stretchr/testify/mock"
)

// NewInvoiceCategoryTotalProvider creates a new instance of InvoiceCategoryTotalProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvoiceCategoryTotalProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvoiceCategoryTotalProvider {
	m := &InvoiceCategoryTotalProvider{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// InvoiceCategoryTotalProvider is an autogenerated mock type for the InvoiceCategoryTotalProvider type
type InvoiceCategoryTotalProvider struct {
	mock.Mock
}

type InvoiceCategoryTotalProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *InvoiceCategoryTotalProvider) EXPECT() *InvoiceCategoryTotalProvider_Expecter {
	return &InvoiceCategoryTotalProvider_Expecter{mock: &_m.Mock}
}

// GetCategoryTotal provides a mock function for the type InvoiceCategoryTotalProvider
func (_mock *InvoiceCategoryTotalProvider) GetCategoryTotal(ctx context.Context, userID vos.UUID, referenceMonth pkgVos.ReferenceMonth, categoryID vos.UUID) (vos.Money, error) {
	ret := _mock.Called(ctx, userID, referenceMonth, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryTotal")
	}

	var r0 vos.Money
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, pkgVos.ReferenceMonth, vos.UUID) (vos.Money, error)); ok {
		return returnFunc(ctx, userID, referenceMonth, categoryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, pkgVos.ReferenceMonth, vos.UUID) vos.Money); ok {
		r0 = returnFunc(ctx, userID, referenceMonth, categoryID)
	} else {
		r0 = ret.Get(0).(vos.Money)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, pkgVos.ReferenceMonth, vos.UUID) error); ok {
		r1 = returnFunc(ctx, userID, referenceMonth, categoryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type InvoiceCategoryTotalProvider_GetCategoryTotal_Call struct {
	*mock.Call
}

func (_e *InvoiceCategoryTotalProvider_Expecter) GetCategoryTotal(ctx interface{}, userID interface{}, referenceMonth interface{}, categoryID interface{}) *InvoiceCategoryTotalProvider_GetCategoryTotal_Call {
	return &InvoiceCategoryTotalProvider_GetCategoryTotal_Call{Call: _e.mock.On("GetCategoryTotal", ctx, userID, referenceMonth, categoryID)}
}

func (_c *InvoiceCategoryTotalProvider_GetCategoryTotal_Call) Run(run func(ctx context.Context, userID vos.UUID, referenceMonth pkgVos.ReferenceMonth, categoryID vos.UUID)) *InvoiceCategoryTotalProvider_GetCategoryTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vos.UUID), args[2].(pkgVos.ReferenceMonth), args[3].(vos.UUID))
	})
	return _c
}

func (_c *InvoiceCategoryTotalProvider_GetCategoryTotal_Call) Return(money vos.Money, err error) *InvoiceCategoryTotalProvider_GetCategoryTotal_Call {
	_c.Call.Return(money, err)
	return _c
}

func (_c *InvoiceCategoryTotalProvider_GetCategoryTotal_Call) Once() *InvoiceCategoryTotalProvider_GetCategoryTotal_Call {
	_c.Call.Once()
	return _c
}
