// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewProcessedEventsRepository creates a new instance of ProcessedEventsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessedEventsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessedEventsRepository {
	m := &ProcessedEventsRepository{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// ProcessedEventsRepository is an autogenerated mock type for the ProcessedEventsRepository type
type ProcessedEventsRepository struct {
	mock.Mock
}

type ProcessedEventsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProcessedEventsRepository) EXPECT() *ProcessedEventsRepository_Expecter {
	return &ProcessedEventsRepository_Expecter{mock: &_m.Mock}
}

// IsProcessed provides a mock function for the type ProcessedEventsRepository
func (_mock *ProcessedEventsRepository) IsProcessed(ctx context.Context, eventID uuid.UUID, consumerName string) (bool, error) {
	ret := _mock.Called(ctx, eventID, consumerName)

	if len(ret) == 0 {
		panic("no return value specified for IsProcessed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = returnFunc(ctx, eventID, consumerName)
	} else {
		r0 = ret.Bool(0)
	}

	var r1 error
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, eventID, consumerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type ProcessedEventsRepository_IsProcessed_Call struct {
	*mock.Call
}

func (_e *ProcessedEventsRepository_Expecter) IsProcessed(ctx any, eventID any, consumerName any) *ProcessedEventsRepository_IsProcessed_Call {
	return &ProcessedEventsRepository_IsProcessed_Call{Call: _e.mock.On("IsProcessed", ctx, eventID, consumerName)}
}

func (_c *ProcessedEventsRepository_IsProcessed_Call) Run(run func(ctx context.Context, eventID uuid.UUID, consumerName string)) *ProcessedEventsRepository_IsProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ProcessedEventsRepository_IsProcessed_Call) Return(result bool, err error) *ProcessedEventsRepository_IsProcessed_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *ProcessedEventsRepository_IsProcessed_Call) Once() *ProcessedEventsRepository_IsProcessed_Call {
	_c.Call.Once()
	return _c
}

// MarkAsProcessed provides a mock function for the type ProcessedEventsRepository
func (_mock *ProcessedEventsRepository) MarkAsProcessed(ctx context.Context, eventID uuid.UUID, consumerName string) error {
	ret := _mock.Called(ctx, eventID, consumerName)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsProcessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, eventID, consumerName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type ProcessedEventsRepository_MarkAsProcessed_Call struct {
	*mock.Call
}

func (_e *ProcessedEventsRepository_Expecter) MarkAsProcessed(ctx any, eventID any, consumerName any) *ProcessedEventsRepository_MarkAsProcessed_Call {
	return &ProcessedEventsRepository_MarkAsProcessed_Call{Call: _e.mock.On("MarkAsProcessed", ctx, eventID, consumerName)}
}

func (_c *ProcessedEventsRepository_MarkAsProcessed_Call) Return(err error) *ProcessedEventsRepository_MarkAsProcessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProcessedEventsRepository_MarkAsProcessed_Call) Once() *ProcessedEventsRepository_MarkAsProcessed_Call {
	_c.Call.Once()
	return _c
}

// TryClaimEvent provides a mock function for the type ProcessedEventsRepository
func (_mock *ProcessedEventsRepository) TryClaimEvent(ctx context.Context, eventID uuid.UUID, consumerName string) (bool, error) {
	ret := _mock.Called(ctx, eventID, consumerName)

	if len(ret) == 0 {
		panic("no return value specified for TryClaimEvent")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = returnFunc(ctx, eventID, consumerName)
	} else {
		r0 = ret.Bool(0)
	}

	var r1 error
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, eventID, consumerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type ProcessedEventsRepository_TryClaimEvent_Call struct {
	*mock.Call
}

func (_e *ProcessedEventsRepository_Expecter) TryClaimEvent(ctx any, eventID any, consumerName any) *ProcessedEventsRepository_TryClaimEvent_Call {
	return &ProcessedEventsRepository_TryClaimEvent_Call{Call: _e.mock.On("TryClaimEvent", ctx, eventID, consumerName)}
}

func (_c *ProcessedEventsRepository_TryClaimEvent_Call) Run(run func(ctx context.Context, eventID uuid.UUID, consumerName string)) *ProcessedEventsRepository_TryClaimEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ProcessedEventsRepository_TryClaimEvent_Call) Return(claimed bool, err error) *ProcessedEventsRepository_TryClaimEvent_Call {
	_c.Call.Return(claimed, err)
	return _c
}

func (_c *ProcessedEventsRepository_TryClaimEvent_Call) Once() *ProcessedEventsRepository_TryClaimEvent_Call {
	_c.Call.Once()
	return _c
}

// DeleteClaim provides a mock function for the type ProcessedEventsRepository
func (_mock *ProcessedEventsRepository) DeleteClaim(ctx context.Context, eventID uuid.UUID, consumerName string) error {
	ret := _mock.Called(ctx, eventID, consumerName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClaim")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, eventID, consumerName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type ProcessedEventsRepository_DeleteClaim_Call struct {
	*mock.Call
}

func (_e *ProcessedEventsRepository_Expecter) DeleteClaim(ctx any, eventID any, consumerName any) *ProcessedEventsRepository_DeleteClaim_Call {
	return &ProcessedEventsRepository_DeleteClaim_Call{Call: _e.mock.On("DeleteClaim", ctx, eventID, consumerName)}
}

func (_c *ProcessedEventsRepository_DeleteClaim_Call) Return(err error) *ProcessedEventsRepository_DeleteClaim_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProcessedEventsRepository_DeleteClaim_Call) Once() *ProcessedEventsRepository_DeleteClaim_Call {
	_c.Call.Once()
	return _c
}

// DeleteOldProcessed provides a mock function for the type ProcessedEventsRepository
func (_mock *ProcessedEventsRepository) DeleteOldProcessed(ctx context.Context, olderThan time.Duration) (int64, error) {
	ret := _mock.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldProcessed")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) int64); ok {
		r0 = returnFunc(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type ProcessedEventsRepository_DeleteOldProcessed_Call struct {
	*mock.Call
}

func (_e *ProcessedEventsRepository_Expecter) DeleteOldProcessed(ctx any, olderThan any) *ProcessedEventsRepository_DeleteOldProcessed_Call {
	return &ProcessedEventsRepository_DeleteOldProcessed_Call{Call: _e.mock.On("DeleteOldProcessed", ctx, olderThan)}
}

func (_c *ProcessedEventsRepository_DeleteOldProcessed_Call) Return(count int64, err error) *ProcessedEventsRepository_DeleteOldProcessed_Call {
	_c.Call.Return(count, err)
	return _c
}

func (_c *ProcessedEventsRepository_DeleteOldProcessed_Call) Once() *ProcessedEventsRepository_DeleteOldProcessed_Call {
	_c.Call.Once()
	return _c
}
