// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewProcessedEventsRepository creates a new instance of ProcessedEventsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessedEventsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessedEventsRepository {
	mock := &ProcessedEventsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProcessedEventsRepository is an autogenerated mock type for the ProcessedEventsRepository type
type ProcessedEventsRepository struct {
	mock.Mock
}

type ProcessedEventsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProcessedEventsRepository) EXPECT() *ProcessedEventsRepository_Expecter {
	return &ProcessedEventsRepository_Expecter{mock: &_m.Mock}
}

// DeleteClaim provides a mock function for the type ProcessedEventsRepository
func (_mock *ProcessedEventsRepository) DeleteClaim(ctx context.Context, eventID uuid.UUID, consumerName string) error {
	ret := _mock.Called(ctx, eventID, consumerName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClaim")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, eventID, consumerName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProcessedEventsRepository_DeleteClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClaim'
type ProcessedEventsRepository_DeleteClaim_Call struct {
	*mock.Call
}

// DeleteClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - consumerName string
func (_e *ProcessedEventsRepository_Expecter) DeleteClaim(ctx interface{}, eventID interface{}, consumerName interface{}) *ProcessedEventsRepository_DeleteClaim_Call {
	return &ProcessedEventsRepository_DeleteClaim_Call{Call: _e.mock.On("DeleteClaim", ctx, eventID, consumerName)}
}

func (_c *ProcessedEventsRepository_DeleteClaim_Call) Run(run func(ctx context.Context, eventID uuid.UUID, consumerName string)) *ProcessedEventsRepository_DeleteClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProcessedEventsRepository_DeleteClaim_Call) Return(err error) *ProcessedEventsRepository_DeleteClaim_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProcessedEventsRepository_DeleteClaim_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID, consumerName string) error) *ProcessedEventsRepository_DeleteClaim_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOldProcessed provides a mock function for the type ProcessedEventsRepository
func (_mock *ProcessedEventsRepository) DeleteOldProcessed(ctx context.Context, olderThan time.Duration) (int64, error) {
	ret := _mock.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldProcessed")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) (int64, error)); ok {
		return returnFunc(ctx, olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) int64); ok {
		r0 = returnFunc(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProcessedEventsRepository_DeleteOldProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOldProcessed'
type ProcessedEventsRepository_DeleteOldProcessed_Call struct {
	*mock.Call
}

// DeleteOldProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Duration
func (_e *ProcessedEventsRepository_Expecter) DeleteOldProcessed(ctx interface{}, olderThan interface{}) *ProcessedEventsRepository_DeleteOldProcessed_Call {
	return &ProcessedEventsRepository_DeleteOldProcessed_Call{Call: _e.mock.On("DeleteOldProcessed", ctx, olderThan)}
}

func (_c *ProcessedEventsRepository_DeleteOldProcessed_Call) Run(run func(ctx context.Context, olderThan time.Duration)) *ProcessedEventsRepository_DeleteOldProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProcessedEventsRepository_DeleteOldProcessed_Call) Return(n int64, err error) *ProcessedEventsRepository_DeleteOldProcessed_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ProcessedEventsRepository_DeleteOldProcessed_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Duration) (int64, error)) *ProcessedEventsRepository_DeleteOldProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// IsProcessed provides a mock function for the type ProcessedEventsRepository
func (_mock *ProcessedEventsRepository) IsProcessed(ctx context.Context, eventID uuid.UUID, consumerName string) (bool, error) {
	ret := _mock.Called(ctx, eventID, consumerName)

	if len(ret) == 0 {
		panic("no return value specified for IsProcessed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return returnFunc(ctx, eventID, consumerName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = returnFunc(ctx, eventID, consumerName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, eventID, consumerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProcessedEventsRepository_IsProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsProcessed'
type ProcessedEventsRepository_IsProcessed_Call struct {
	*mock.Call
}

// IsProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - consumerName string
func (_e *ProcessedEventsRepository_Expecter) IsProcessed(ctx interface{}, eventID interface{}, consumerName interface{}) *ProcessedEventsRepository_IsProcessed_Call {
	return &ProcessedEventsRepository_IsProcessed_Call{Call: _e.mock.On("IsProcessed", ctx, eventID, consumerName)}
}

func (_c *ProcessedEventsRepository_IsProcessed_Call) Run(run func(ctx context.Context, eventID uuid.UUID, consumerName string)) *ProcessedEventsRepository_IsProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProcessedEventsRepository_IsProcessed_Call) Return(b bool, err error) *ProcessedEventsRepository_IsProcessed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *ProcessedEventsRepository_IsProcessed_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID, consumerName string) (bool, error)) *ProcessedEventsRepository_IsProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsProcessed provides a mock function for the type ProcessedEventsRepository
func (_mock *ProcessedEventsRepository) MarkAsProcessed(ctx context.Context, eventID uuid.UUID, consumerName string) error {
	ret := _mock.Called(ctx, eventID, consumerName)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsProcessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, eventID, consumerName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProcessedEventsRepository_MarkAsProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsProcessed'
type ProcessedEventsRepository_MarkAsProcessed_Call struct {
	*mock.Call
}

// MarkAsProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - consumerName string
func (_e *ProcessedEventsRepository_Expecter) MarkAsProcessed(ctx interface{}, eventID interface{}, consumerName interface{}) *ProcessedEventsRepository_MarkAsProcessed_Call {
	return &ProcessedEventsRepository_MarkAsProcessed_Call{Call: _e.mock.On("MarkAsProcessed", ctx, eventID, consumerName)}
}

func (_c *ProcessedEventsRepository_MarkAsProcessed_Call) Run(run func(ctx context.Context, eventID uuid.UUID, consumerName string)) *ProcessedEventsRepository_MarkAsProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProcessedEventsRepository_MarkAsProcessed_Call) Return(err error) *ProcessedEventsRepository_MarkAsProcessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProcessedEventsRepository_MarkAsProcessed_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID, consumerName string) error) *ProcessedEventsRepository_MarkAsProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// TryClaimEvent provides a mock function for the type ProcessedEventsRepository
func (_mock *ProcessedEventsRepository) TryClaimEvent(ctx context.Context, eventID uuid.UUID, consumerName string) (bool, error) {
	ret := _mock.Called(ctx, eventID, consumerName)

	if len(ret) == 0 {
		panic("no return value specified for TryClaimEvent")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return returnFunc(ctx, eventID, consumerName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = returnFunc(ctx, eventID, consumerName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, eventID, consumerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProcessedEventsRepository_TryClaimEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryClaimEvent'
type ProcessedEventsRepository_TryClaimEvent_Call struct {
	*mock.Call
}

// TryClaimEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - consumerName string
func (_e *ProcessedEventsRepository_Expecter) TryClaimEvent(ctx interface{}, eventID interface{}, consumerName interface{}) *ProcessedEventsRepository_TryClaimEvent_Call {
	return &ProcessedEventsRepository_TryClaimEvent_Call{Call: _e.mock.On("TryClaimEvent", ctx, eventID, consumerName)}
}

func (_c *ProcessedEventsRepository_TryClaimEvent_Call) Run(run func(ctx context.Context, eventID uuid.UUID, consumerName string)) *ProcessedEventsRepository_TryClaimEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProcessedEventsRepository_TryClaimEvent_Call) Return(b bool, err error) *ProcessedEventsRepository_TryClaimEvent_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *ProcessedEventsRepository_TryClaimEvent_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID, consumerName string) (bool, error)) *ProcessedEventsRepository_TryClaimEvent_Call {
	_c.Call.Return(run)
	return _c
}
