// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"

	"github.com/jailtonjunior94/financial/internal/budget/domain/entities"
	"github.com/jailtonjunior94/financial/internal/budget/domain/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewReplicateBudgetUseCase creates a new instance of ReplicateBudgetUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReplicateBudgetUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReplicateBudgetUseCase {
	m := &ReplicateBudgetUseCase{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// ReplicateBudgetUseCase is an autogenerated mock type for the ReplicateBudgetUseCase type
type ReplicateBudgetUseCase struct {
	mock.Mock
}

type ReplicateBudgetUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *ReplicateBudgetUseCase) EXPECT() *ReplicateBudgetUseCase_Expecter {
	return &ReplicateBudgetUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type ReplicateBudgetUseCase
func (_mock *ReplicateBudgetUseCase) Execute(ctx context.Context, repository interfaces.BudgetRepository, sourceBudget *entities.Budget) error {
	ret := _mock.Called(ctx, repository, sourceBudget)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.BudgetRepository, *entities.Budget) error); ok {
		r0 = returnFunc(ctx, repository, sourceBudget)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReplicateBudgetUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ReplicateBudgetUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - repository interfaces.BudgetRepository
//   - sourceBudget *entities.Budget
func (_e *ReplicateBudgetUseCase_Expecter) Execute(ctx interface{}, repository interface{}, sourceBudget interface{}) *ReplicateBudgetUseCase_Execute_Call {
	return &ReplicateBudgetUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, repository, sourceBudget)}
}

func (_c *ReplicateBudgetUseCase_Execute_Call) Run(run func(ctx context.Context, repository interfaces.BudgetRepository, sourceBudget *entities.Budget)) *ReplicateBudgetUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.BudgetRepository
		if args[1] != nil {
			arg1 = args[1].(interfaces.BudgetRepository)
		}
		var arg2 *entities.Budget
		if args[2] != nil {
			arg2 = args[2].(*entities.Budget)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *ReplicateBudgetUseCase_Execute_Call) Return(err error) *ReplicateBudgetUseCase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReplicateBudgetUseCase_Execute_Call) RunAndReturn(run func(context.Context, interfaces.BudgetRepository, *entities.Budget) error) *ReplicateBudgetUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

func (_c *ReplicateBudgetUseCase_Execute_Call) Once() *ReplicateBudgetUseCase_Execute_Call {
	_c.Call.Once()
	return _c
}

func (_c *ReplicateBudgetUseCase_Execute_Call) Times(i int) *ReplicateBudgetUseCase_Execute_Call {
	_c.Call.Times(i)
	return _c
}
