// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	vos0 "github.com/jailtonjunior94/financial/pkg/domain/vos"
	mock "github.com/stretchr/testify/mock"
)

// NewSyncBudgetSpentAmountUseCase creates a new instance of SyncBudgetSpentAmountUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncBudgetSpentAmountUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SyncBudgetSpentAmountUseCase {
	mock := &SyncBudgetSpentAmountUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SyncBudgetSpentAmountUseCase is an autogenerated mock type for the SyncBudgetSpentAmountUseCase type
type SyncBudgetSpentAmountUseCase struct {
	mock.Mock
}

type SyncBudgetSpentAmountUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *SyncBudgetSpentAmountUseCase) EXPECT() *SyncBudgetSpentAmountUseCase_Expecter {
	return &SyncBudgetSpentAmountUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type SyncBudgetSpentAmountUseCase
func (_mock *SyncBudgetSpentAmountUseCase) Execute(ctx context.Context, userID vos.UUID, referenceMonth vos0.ReferenceMonth, categoryID vos.UUID) error {
	ret := _mock.Called(ctx, userID, referenceMonth, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos0.ReferenceMonth, vos.UUID) error); ok {
		r0 = returnFunc(ctx, userID, referenceMonth, categoryID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SyncBudgetSpentAmountUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type SyncBudgetSpentAmountUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
//   - referenceMonth vos0.ReferenceMonth
//   - categoryID vos.UUID
func (_e *SyncBudgetSpentAmountUseCase_Expecter) Execute(ctx interface{}, userID interface{}, referenceMonth interface{}, categoryID interface{}) *SyncBudgetSpentAmountUseCase_Execute_Call {
	return &SyncBudgetSpentAmountUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, referenceMonth, categoryID)}
}

func (_c *SyncBudgetSpentAmountUseCase_Execute_Call) Run(run func(ctx context.Context, userID vos.UUID, referenceMonth vos0.ReferenceMonth, categoryID vos.UUID)) *SyncBudgetSpentAmountUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		var arg2 vos0.ReferenceMonth
		if args[2] != nil {
			arg2 = args[2].(vos0.ReferenceMonth)
		}
		var arg3 vos.UUID
		if args[3] != nil {
			arg3 = args[3].(vos.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SyncBudgetSpentAmountUseCase_Execute_Call) Return(err error) *SyncBudgetSpentAmountUseCase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SyncBudgetSpentAmountUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, referenceMonth vos0.ReferenceMonth, categoryID vos.UUID) error) *SyncBudgetSpentAmountUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
