// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	mock "github.com/stretchr/testify/mock"

	pkgVos "github.com/jailtonjunior94/financial/pkg/domain/vos"
)

// NewSyncBudgetSpentAmountUseCase creates a new instance of SyncBudgetSpentAmountUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncBudgetSpentAmountUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SyncBudgetSpentAmountUseCase {
	m := &SyncBudgetSpentAmountUseCase{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// SyncBudgetSpentAmountUseCase is an autogenerated mock type for the SyncBudgetSpentAmountUseCase type
type SyncBudgetSpentAmountUseCase struct {
	mock.Mock
}

type SyncBudgetSpentAmountUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *SyncBudgetSpentAmountUseCase) EXPECT() *SyncBudgetSpentAmountUseCase_Expecter {
	return &SyncBudgetSpentAmountUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type SyncBudgetSpentAmountUseCase
func (_mock *SyncBudgetSpentAmountUseCase) Execute(ctx context.Context, userID vos.UUID, referenceMonth pkgVos.ReferenceMonth, categoryID vos.UUID) error {
	ret := _mock.Called(ctx, userID, referenceMonth, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, pkgVos.ReferenceMonth, vos.UUID) error); ok {
		r0 = returnFunc(ctx, userID, referenceMonth, categoryID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type SyncBudgetSpentAmountUseCase_Execute_Call struct {
	*mock.Call
}

func (_e *SyncBudgetSpentAmountUseCase_Expecter) Execute(ctx any, userID any, referenceMonth any, categoryID any) *SyncBudgetSpentAmountUseCase_Execute_Call {
	return &SyncBudgetSpentAmountUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, referenceMonth, categoryID)}
}

func (_c *SyncBudgetSpentAmountUseCase_Execute_Call) Run(run func(ctx context.Context, userID vos.UUID, referenceMonth pkgVos.ReferenceMonth, categoryID vos.UUID)) *SyncBudgetSpentAmountUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vos.UUID), args[2].(pkgVos.ReferenceMonth), args[3].(vos.UUID))
	})
	return _c
}

func (_c *SyncBudgetSpentAmountUseCase_Execute_Call) Return(err error) *SyncBudgetSpentAmountUseCase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SyncBudgetSpentAmountUseCase_Execute_Call) Once() *SyncBudgetSpentAmountUseCase_Execute_Call {
	_c.Call.Once()
	return _c
}

func (_c *SyncBudgetSpentAmountUseCase_Execute_Call) Times(i int) *SyncBudgetSpentAmountUseCase_Execute_Call {
	_c.Call.Times(i)
	return _c
}
