apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: financial
  name: financial-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: financial
    spec:
      containers:
        - name: financial
          image: jailtonjunior/financial:3.0.0
          args: ["api"]
          resources:
            limits:
              cpu: "50m"
              memory: "128Mi"
          envFrom:
            - configMapRef:
                name: financial-config
          ports:
            - containerPort: 8000
