apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: financial-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: financial-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
