// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/database"
	"github.com/google/uuid"
	"github.com/jailtonjunior94/financial/pkg/outbox"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// SaveDomainEvent provides a mock function for the type Service
func (_mock *Service) SaveDomainEvent(ctx context.Context, tx database.DBTX, aggregateID uuid.UUID, aggregateType string, eventType string, payload outbox.JSONBPayload) error {
	ret := _mock.Called(ctx, tx, aggregateID, aggregateType, eventType, payload)

	if len(ret) == 0 {
		panic("no return value specified for SaveDomainEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, uuid.UUID, string, string, outbox.JSONBPayload) error); ok {
		r0 = returnFunc(ctx, tx, aggregateID, aggregateType, eventType, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_SaveDomainEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDomainEvent'
type Service_SaveDomainEvent_Call struct {
	*mock.Call
}

// SaveDomainEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - tx database.DBTX
//   - aggregateID uuid.UUID
//   - aggregateType string
//   - eventType string
//   - payload outbox.JSONBPayload
func (_e *Service_Expecter) SaveDomainEvent(ctx interface{}, tx interface{}, aggregateID interface{}, aggregateType interface{}, eventType interface{}, payload interface{}) *Service_SaveDomainEvent_Call {
	return &Service_SaveDomainEvent_Call{Call: _e.mock.On("SaveDomainEvent", ctx, tx, aggregateID, aggregateType, eventType, payload)}
}

func (_c *Service_SaveDomainEvent_Call) Run(run func(ctx context.Context, tx database.DBTX, aggregateID uuid.UUID, aggregateType string, eventType string, payload outbox.JSONBPayload)) *Service_SaveDomainEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 outbox.JSONBPayload
		if args[5] != nil {
			arg5 = args[5].(outbox.JSONBPayload)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *Service_SaveDomainEvent_Call) Return(err error) *Service_SaveDomainEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_SaveDomainEvent_Call) RunAndReturn(run func(ctx context.Context, tx database.DBTX, aggregateID uuid.UUID, aggregateType string, eventType string, payload outbox.JSONBPayload) error) *Service_SaveDomainEvent_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEvent provides a mock function for the type Service
func (_mock *Service) SaveEvent(ctx context.Context, tx database.DBTX, event *outbox.OutboxEvent) error {
	ret := _mock.Called(ctx, tx, event)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, *outbox.OutboxEvent) error); ok {
		r0 = returnFunc(ctx, tx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_SaveEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvent'
type Service_SaveEvent_Call struct {
	*mock.Call
}

// SaveEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - tx database.DBTX
//   - event *outbox.OutboxEvent
func (_e *Service_Expecter) SaveEvent(ctx interface{}, tx interface{}, event interface{}) *Service_SaveEvent_Call {
	return &Service_SaveEvent_Call{Call: _e.mock.On("SaveEvent", ctx, tx, event)}
}

func (_c *Service_SaveEvent_Call) Run(run func(ctx context.Context, tx database.DBTX, event *outbox.OutboxEvent)) *Service_SaveEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 *outbox.OutboxEvent
		if args[2] != nil {
			arg2 = args[2].(*outbox.OutboxEvent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_SaveEvent_Call) Return(err error) *Service_SaveEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_SaveEvent_Call) RunAndReturn(run func(ctx context.Context, tx database.DBTX, event *outbox.OutboxEvent) error) *Service_SaveEvent_Call {
	_c.Call.Return(run)
	return _c
}
