// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	"github.com/jailtonjunior94/financial/internal/payment_method/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewPaymentMethodRepository creates a new instance of PaymentMethodRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentMethodRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentMethodRepository {
	mock := &PaymentMethodRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentMethodRepository is an autogenerated mock type for the PaymentMethodRepository type
type PaymentMethodRepository struct {
	mock.Mock
}

type PaymentMethodRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentMethodRepository) EXPECT() *PaymentMethodRepository_Expecter {
	return &PaymentMethodRepository_Expecter{mock: &_m.Mock}
}

// FindByCode provides a mock function for the type PaymentMethodRepository
func (_mock *PaymentMethodRepository) FindByCode(ctx context.Context, code string) (*entities.PaymentMethod, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *entities.PaymentMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.PaymentMethod, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.PaymentMethod); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PaymentMethod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentMethodRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type PaymentMethodRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *PaymentMethodRepository_Expecter) FindByCode(ctx interface{}, code interface{}) *PaymentMethodRepository_FindByCode_Call {
	return &PaymentMethodRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *PaymentMethodRepository_FindByCode_Call) Run(run func(ctx context.Context, code string)) *PaymentMethodRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentMethodRepository_FindByCode_Call) Return(paymentMethod *entities.PaymentMethod, err error) *PaymentMethodRepository_FindByCode_Call {
	_c.Call.Return(paymentMethod, err)
	return _c
}

func (_c *PaymentMethodRepository_FindByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*entities.PaymentMethod, error)) *PaymentMethodRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type PaymentMethodRepository
func (_mock *PaymentMethodRepository) FindByID(ctx context.Context, id vos.UUID) (*entities.PaymentMethod, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.PaymentMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) (*entities.PaymentMethod, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) *entities.PaymentMethod); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PaymentMethod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentMethodRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type PaymentMethodRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id vos.UUID
func (_e *PaymentMethodRepository_Expecter) FindByID(ctx interface{}, id interface{}) *PaymentMethodRepository_FindByID_Call {
	return &PaymentMethodRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *PaymentMethodRepository_FindByID_Call) Run(run func(ctx context.Context, id vos.UUID)) *PaymentMethodRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentMethodRepository_FindByID_Call) Return(paymentMethod *entities.PaymentMethod, err error) *PaymentMethodRepository_FindByID_Call {
	_c.Call.Return(paymentMethod, err)
	return _c
}

func (_c *PaymentMethodRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id vos.UUID) (*entities.PaymentMethod, error)) *PaymentMethodRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type PaymentMethodRepository
func (_mock *PaymentMethodRepository) List(ctx context.Context) ([]*entities.PaymentMethod, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.PaymentMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entities.PaymentMethod, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entities.PaymentMethod); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.PaymentMethod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentMethodRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PaymentMethodRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PaymentMethodRepository_Expecter) List(ctx interface{}) *PaymentMethodRepository_List_Call {
	return &PaymentMethodRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *PaymentMethodRepository_List_Call) Run(run func(ctx context.Context)) *PaymentMethodRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PaymentMethodRepository_List_Call) Return(paymentMethods []*entities.PaymentMethod, err error) *PaymentMethodRepository_List_Call {
	_c.Call.Return(paymentMethods, err)
	return _c
}

func (_c *PaymentMethodRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*entities.PaymentMethod, error)) *PaymentMethodRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type PaymentMethodRepository
func (_mock *PaymentMethodRepository) Save(ctx context.Context, paymentMethod *entities.PaymentMethod) error {
	ret := _mock.Called(ctx, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.PaymentMethod) error); ok {
		r0 = returnFunc(ctx, paymentMethod)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PaymentMethodRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type PaymentMethodRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentMethod *entities.PaymentMethod
func (_e *PaymentMethodRepository_Expecter) Save(ctx interface{}, paymentMethod interface{}) *PaymentMethodRepository_Save_Call {
	return &PaymentMethodRepository_Save_Call{Call: _e.mock.On("Save", ctx, paymentMethod)}
}

func (_c *PaymentMethodRepository_Save_Call) Run(run func(ctx context.Context, paymentMethod *entities.PaymentMethod)) *PaymentMethodRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.PaymentMethod
		if args[1] != nil {
			arg1 = args[1].(*entities.PaymentMethod)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentMethodRepository_Save_Call) Return(err error) *PaymentMethodRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PaymentMethodRepository_Save_Call) RunAndReturn(run func(ctx context.Context, paymentMethod *entities.PaymentMethod) error) *PaymentMethodRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type PaymentMethodRepository
func (_mock *PaymentMethodRepository) Update(ctx context.Context, paymentMethod *entities.PaymentMethod) error {
	ret := _mock.Called(ctx, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.PaymentMethod) error); ok {
		r0 = returnFunc(ctx, paymentMethod)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PaymentMethodRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PaymentMethodRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentMethod *entities.PaymentMethod
func (_e *PaymentMethodRepository_Expecter) Update(ctx interface{}, paymentMethod interface{}) *PaymentMethodRepository_Update_Call {
	return &PaymentMethodRepository_Update_Call{Call: _e.mock.On("Update", ctx, paymentMethod)}
}

func (_c *PaymentMethodRepository_Update_Call) Run(run func(ctx context.Context, paymentMethod *entities.PaymentMethod)) *PaymentMethodRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.PaymentMethod
		if args[1] != nil {
			arg1 = args[1].(*entities.PaymentMethod)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentMethodRepository_Update_Call) Return(err error) *PaymentMethodRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PaymentMethodRepository_Update_Call) RunAndReturn(run func(ctx context.Context, paymentMethod *entities.PaymentMethod) error) *PaymentMethodRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
