// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	"github.com/jailtonjunior94/financial/internal/invoice/domain/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewCardProvider creates a new instance of CardProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardProvider {
	mock := &CardProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CardProvider is an autogenerated mock type for the CardProvider type
type CardProvider struct {
	mock.Mock
}

type CardProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *CardProvider) EXPECT() *CardProvider_Expecter {
	return &CardProvider_Expecter{mock: &_m.Mock}
}

// GetCardBillingInfo provides a mock function for the type CardProvider
func (_mock *CardProvider) GetCardBillingInfo(ctx context.Context, userID vos.UUID, cardID vos.UUID) (*interfaces.CardBillingInfo, error) {
	ret := _mock.Called(ctx, userID, cardID)

	if len(ret) == 0 {
		panic("no return value specified for GetCardBillingInfo")
	}

	var r0 *interfaces.CardBillingInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID) (*interfaces.CardBillingInfo, error)); ok {
		return returnFunc(ctx, userID, cardID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID) *interfaces.CardBillingInfo); ok {
		r0 = returnFunc(ctx, userID, cardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.CardBillingInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, vos.UUID) error); ok {
		r1 = returnFunc(ctx, userID, cardID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardProvider_GetCardBillingInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCardBillingInfo'
type CardProvider_GetCardBillingInfo_Call struct {
	*mock.Call
}

// GetCardBillingInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
//   - cardID vos.UUID
func (_e *CardProvider_Expecter) GetCardBillingInfo(ctx interface{}, userID interface{}, cardID interface{}) *CardProvider_GetCardBillingInfo_Call {
	return &CardProvider_GetCardBillingInfo_Call{Call: _e.mock.On("GetCardBillingInfo", ctx, userID, cardID)}
}

func (_c *CardProvider_GetCardBillingInfo_Call) Run(run func(ctx context.Context, userID vos.UUID, cardID vos.UUID)) *CardProvider_GetCardBillingInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		var arg2 vos.UUID
		if args[2] != nil {
			arg2 = args[2].(vos.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CardProvider_GetCardBillingInfo_Call) Return(cardBillingInfo *interfaces.CardBillingInfo, err error) *CardProvider_GetCardBillingInfo_Call {
	_c.Call.Return(cardBillingInfo, err)
	return _c
}

func (_c *CardProvider_GetCardBillingInfo_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, cardID vos.UUID) (*interfaces.CardBillingInfo, error)) *CardProvider_GetCardBillingInfo_Call {
	_c.Call.Return(run)
	return _c
}
