// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	"github.com/jailtonjunior94/financial/internal/invoice/domain/entities"
	"github.com/jailtonjunior94/financial/internal/invoice/domain/interfaces"
	vos0 "github.com/jailtonjunior94/financial/pkg/domain/vos"
	mock "github.com/stretchr/testify/mock"
)

// NewInvoiceRepository creates a new instance of InvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvoiceRepository {
	mock := &InvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InvoiceRepository is an autogenerated mock type for the InvoiceRepository type
type InvoiceRepository struct {
	mock.Mock
}

type InvoiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InvoiceRepository) EXPECT() *InvoiceRepository_Expecter {
	return &InvoiceRepository_Expecter{mock: &_m.Mock}
}

// DeleteItem provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) DeleteItem(ctx context.Context, itemID vos.UUID) error {
	ret := _mock.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) error); ok {
		r0 = returnFunc(ctx, itemID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvoiceRepository_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type InvoiceRepository_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID vos.UUID
func (_e *InvoiceRepository_Expecter) DeleteItem(ctx interface{}, itemID interface{}) *InvoiceRepository_DeleteItem_Call {
	return &InvoiceRepository_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, itemID)}
}

func (_c *InvoiceRepository_DeleteItem_Call) Run(run func(ctx context.Context, itemID vos.UUID)) *InvoiceRepository_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceRepository_DeleteItem_Call) Return(err error) *InvoiceRepository_DeleteItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvoiceRepository_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, itemID vos.UUID) error) *InvoiceRepository_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCard provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) FindByCard(ctx context.Context, cardID vos.UUID) ([]*entities.Invoice, error) {
	ret := _mock.Called(ctx, cardID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCard")
	}

	var r0 []*entities.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) ([]*entities.Invoice, error)); ok {
		return returnFunc(ctx, cardID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) []*entities.Invoice); ok {
		r0 = returnFunc(ctx, cardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID) error); ok {
		r1 = returnFunc(ctx, cardID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceRepository_FindByCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCard'
type InvoiceRepository_FindByCard_Call struct {
	*mock.Call
}

// FindByCard is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID vos.UUID
func (_e *InvoiceRepository_Expecter) FindByCard(ctx interface{}, cardID interface{}) *InvoiceRepository_FindByCard_Call {
	return &InvoiceRepository_FindByCard_Call{Call: _e.mock.On("FindByCard", ctx, cardID)}
}

func (_c *InvoiceRepository_FindByCard_Call) Run(run func(ctx context.Context, cardID vos.UUID)) *InvoiceRepository_FindByCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceRepository_FindByCard_Call) Return(invoices []*entities.Invoice, err error) *InvoiceRepository_FindByCard_Call {
	_c.Call.Return(invoices, err)
	return _c
}

func (_c *InvoiceRepository_FindByCard_Call) RunAndReturn(run func(ctx context.Context, cardID vos.UUID) ([]*entities.Invoice, error)) *InvoiceRepository_FindByCard_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) FindByID(ctx context.Context, id vos.UUID) (*entities.Invoice, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) (*entities.Invoice, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) *entities.Invoice); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type InvoiceRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id vos.UUID
func (_e *InvoiceRepository_Expecter) FindByID(ctx interface{}, id interface{}) *InvoiceRepository_FindByID_Call {
	return &InvoiceRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *InvoiceRepository_FindByID_Call) Run(run func(ctx context.Context, id vos.UUID)) *InvoiceRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceRepository_FindByID_Call) Return(invoice *entities.Invoice, err error) *InvoiceRepository_FindByID_Call {
	_c.Call.Return(invoice, err)
	return _c
}

func (_c *InvoiceRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id vos.UUID) (*entities.Invoice, error)) *InvoiceRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserAndCardAndMonth provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) FindByUserAndCardAndMonth(ctx context.Context, userID vos.UUID, cardID vos.UUID, referenceMonth vos0.ReferenceMonth) (*entities.Invoice, error) {
	ret := _mock.Called(ctx, userID, cardID, referenceMonth)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndCardAndMonth")
	}

	var r0 *entities.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID, vos0.ReferenceMonth) (*entities.Invoice, error)); ok {
		return returnFunc(ctx, userID, cardID, referenceMonth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID, vos0.ReferenceMonth) *entities.Invoice); ok {
		r0 = returnFunc(ctx, userID, cardID, referenceMonth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, vos.UUID, vos0.ReferenceMonth) error); ok {
		r1 = returnFunc(ctx, userID, cardID, referenceMonth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceRepository_FindByUserAndCardAndMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserAndCardAndMonth'
type InvoiceRepository_FindByUserAndCardAndMonth_Call struct {
	*mock.Call
}

// FindByUserAndCardAndMonth is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
//   - cardID vos.UUID
//   - referenceMonth vos0.ReferenceMonth
func (_e *InvoiceRepository_Expecter) FindByUserAndCardAndMonth(ctx interface{}, userID interface{}, cardID interface{}, referenceMonth interface{}) *InvoiceRepository_FindByUserAndCardAndMonth_Call {
	return &InvoiceRepository_FindByUserAndCardAndMonth_Call{Call: _e.mock.On("FindByUserAndCardAndMonth", ctx, userID, cardID, referenceMonth)}
}

func (_c *InvoiceRepository_FindByUserAndCardAndMonth_Call) Run(run func(ctx context.Context, userID vos.UUID, cardID vos.UUID, referenceMonth vos0.ReferenceMonth)) *InvoiceRepository_FindByUserAndCardAndMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		var arg2 vos.UUID
		if args[2] != nil {
			arg2 = args[2].(vos.UUID)
		}
		var arg3 vos0.ReferenceMonth
		if args[3] != nil {
			arg3 = args[3].(vos0.ReferenceMonth)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *InvoiceRepository_FindByUserAndCardAndMonth_Call) Return(invoice *entities.Invoice, err error) *InvoiceRepository_FindByUserAndCardAndMonth_Call {
	_c.Call.Return(invoice, err)
	return _c
}

func (_c *InvoiceRepository_FindByUserAndCardAndMonth_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, cardID vos.UUID, referenceMonth vos0.ReferenceMonth) (*entities.Invoice, error)) *InvoiceRepository_FindByUserAndCardAndMonth_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserAndMonth provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) FindByUserAndMonth(ctx context.Context, userID vos.UUID, referenceMonth vos0.ReferenceMonth) ([]*entities.Invoice, error) {
	ret := _mock.Called(ctx, userID, referenceMonth)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndMonth")
	}

	var r0 []*entities.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos0.ReferenceMonth) ([]*entities.Invoice, error)); ok {
		return returnFunc(ctx, userID, referenceMonth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos0.ReferenceMonth) []*entities.Invoice); ok {
		r0 = returnFunc(ctx, userID, referenceMonth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, vos0.ReferenceMonth) error); ok {
		r1 = returnFunc(ctx, userID, referenceMonth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceRepository_FindByUserAndMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserAndMonth'
type InvoiceRepository_FindByUserAndMonth_Call struct {
	*mock.Call
}

// FindByUserAndMonth is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
//   - referenceMonth vos0.ReferenceMonth
func (_e *InvoiceRepository_Expecter) FindByUserAndMonth(ctx interface{}, userID interface{}, referenceMonth interface{}) *InvoiceRepository_FindByUserAndMonth_Call {
	return &InvoiceRepository_FindByUserAndMonth_Call{Call: _e.mock.On("FindByUserAndMonth", ctx, userID, referenceMonth)}
}

func (_c *InvoiceRepository_FindByUserAndMonth_Call) Run(run func(ctx context.Context, userID vos.UUID, referenceMonth vos0.ReferenceMonth)) *InvoiceRepository_FindByUserAndMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		var arg2 vos0.ReferenceMonth
		if args[2] != nil {
			arg2 = args[2].(vos0.ReferenceMonth)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InvoiceRepository_FindByUserAndMonth_Call) Return(invoices []*entities.Invoice, err error) *InvoiceRepository_FindByUserAndMonth_Call {
	_c.Call.Return(invoices, err)
	return _c
}

func (_c *InvoiceRepository_FindByUserAndMonth_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, referenceMonth vos0.ReferenceMonth) ([]*entities.Invoice, error)) *InvoiceRepository_FindByUserAndMonth_Call {
	_c.Call.Return(run)
	return _c
}

// FindItemsByPurchaseOrigin provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) FindItemsByPurchaseOrigin(ctx context.Context, purchaseDate string, categoryID vos.UUID, description string) ([]*entities.InvoiceItem, error) {
	ret := _mock.Called(ctx, purchaseDate, categoryID, description)

	if len(ret) == 0 {
		panic("no return value specified for FindItemsByPurchaseOrigin")
	}

	var r0 []*entities.InvoiceItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, vos.UUID, string) ([]*entities.InvoiceItem, error)); ok {
		return returnFunc(ctx, purchaseDate, categoryID, description)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, vos.UUID, string) []*entities.InvoiceItem); ok {
		r0 = returnFunc(ctx, purchaseDate, categoryID, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.InvoiceItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, vos.UUID, string) error); ok {
		r1 = returnFunc(ctx, purchaseDate, categoryID, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceRepository_FindItemsByPurchaseOrigin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindItemsByPurchaseOrigin'
type InvoiceRepository_FindItemsByPurchaseOrigin_Call struct {
	*mock.Call
}

// FindItemsByPurchaseOrigin is a helper method to define mock.On call
//   - ctx context.Context
//   - purchaseDate string
//   - categoryID vos.UUID
//   - description string
func (_e *InvoiceRepository_Expecter) FindItemsByPurchaseOrigin(ctx interface{}, purchaseDate interface{}, categoryID interface{}, description interface{}) *InvoiceRepository_FindItemsByPurchaseOrigin_Call {
	return &InvoiceRepository_FindItemsByPurchaseOrigin_Call{Call: _e.mock.On("FindItemsByPurchaseOrigin", ctx, purchaseDate, categoryID, description)}
}

func (_c *InvoiceRepository_FindItemsByPurchaseOrigin_Call) Run(run func(ctx context.Context, purchaseDate string, categoryID vos.UUID, description string)) *InvoiceRepository_FindItemsByPurchaseOrigin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 vos.UUID
		if args[2] != nil {
			arg2 = args[2].(vos.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *InvoiceRepository_FindItemsByPurchaseOrigin_Call) Return(invoiceItems []*entities.InvoiceItem, err error) *InvoiceRepository_FindItemsByPurchaseOrigin_Call {
	_c.Call.Return(invoiceItems, err)
	return _c
}

func (_c *InvoiceRepository_FindItemsByPurchaseOrigin_Call) RunAndReturn(run func(ctx context.Context, purchaseDate string, categoryID vos.UUID, description string) ([]*entities.InvoiceItem, error)) *InvoiceRepository_FindItemsByPurchaseOrigin_Call {
	_c.Call.Return(run)
	return _c
}

// FindStatus provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) FindStatus(ctx context.Context, invoiceID vos.UUID) (string, error) {
	ret := _mock.Called(ctx, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for FindStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) (string, error)); ok {
		return returnFunc(ctx, invoiceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) string); ok {
		r0 = returnFunc(ctx, invoiceID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID) error); ok {
		r1 = returnFunc(ctx, invoiceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceRepository_FindStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindStatus'
type InvoiceRepository_FindStatus_Call struct {
	*mock.Call
}

// FindStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID vos.UUID
func (_e *InvoiceRepository_Expecter) FindStatus(ctx interface{}, invoiceID interface{}) *InvoiceRepository_FindStatus_Call {
	return &InvoiceRepository_FindStatus_Call{Call: _e.mock.On("FindStatus", ctx, invoiceID)}
}

func (_c *InvoiceRepository_FindStatus_Call) Run(run func(ctx context.Context, invoiceID vos.UUID)) *InvoiceRepository_FindStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceRepository_FindStatus_Call) Return(s string, err error) *InvoiceRepository_FindStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *InvoiceRepository_FindStatus_Call) RunAndReturn(run func(ctx context.Context, invoiceID vos.UUID) (string, error)) *InvoiceRepository_FindStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) Insert(ctx context.Context, invoice *entities.Invoice) error {
	ret := _mock.Called(ctx, invoice)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Invoice) error); ok {
		r0 = returnFunc(ctx, invoice)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvoiceRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type InvoiceRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - invoice *entities.Invoice
func (_e *InvoiceRepository_Expecter) Insert(ctx interface{}, invoice interface{}) *InvoiceRepository_Insert_Call {
	return &InvoiceRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, invoice)}
}

func (_c *InvoiceRepository_Insert_Call) Run(run func(ctx context.Context, invoice *entities.Invoice)) *InvoiceRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Invoice
		if args[1] != nil {
			arg1 = args[1].(*entities.Invoice)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceRepository_Insert_Call) Return(err error) *InvoiceRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvoiceRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, invoice *entities.Invoice) error) *InvoiceRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertItems provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) InsertItems(ctx context.Context, items []*entities.InvoiceItem) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for InsertItems")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entities.InvoiceItem) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvoiceRepository_InsertItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertItems'
type InvoiceRepository_InsertItems_Call struct {
	*mock.Call
}

// InsertItems is a helper method to define mock.On call
//   - ctx context.Context
//   - items []*entities.InvoiceItem
func (_e *InvoiceRepository_Expecter) InsertItems(ctx interface{}, items interface{}) *InvoiceRepository_InsertItems_Call {
	return &InvoiceRepository_InsertItems_Call{Call: _e.mock.On("InsertItems", ctx, items)}
}

func (_c *InvoiceRepository_InsertItems_Call) Run(run func(ctx context.Context, items []*entities.InvoiceItem)) *InvoiceRepository_InsertItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entities.InvoiceItem
		if args[1] != nil {
			arg1 = args[1].([]*entities.InvoiceItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceRepository_InsertItems_Call) Return(err error) *InvoiceRepository_InsertItems_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvoiceRepository_InsertItems_Call) RunAndReturn(run func(ctx context.Context, items []*entities.InvoiceItem) error) *InvoiceRepository_InsertItems_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCard provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) ListByCard(ctx context.Context, params interfaces.ListInvoicesByCardParams) ([]*entities.Invoice, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListByCard")
	}

	var r0 []*entities.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListInvoicesByCardParams) ([]*entities.Invoice, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListInvoicesByCardParams) []*entities.Invoice); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.ListInvoicesByCardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceRepository_ListByCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCard'
type InvoiceRepository_ListByCard_Call struct {
	*mock.Call
}

// ListByCard is a helper method to define mock.On call
//   - ctx context.Context
//   - params interfaces.ListInvoicesByCardParams
func (_e *InvoiceRepository_Expecter) ListByCard(ctx interface{}, params interface{}) *InvoiceRepository_ListByCard_Call {
	return &InvoiceRepository_ListByCard_Call{Call: _e.mock.On("ListByCard", ctx, params)}
}

func (_c *InvoiceRepository_ListByCard_Call) Run(run func(ctx context.Context, params interfaces.ListInvoicesByCardParams)) *InvoiceRepository_ListByCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.ListInvoicesByCardParams
		if args[1] != nil {
			arg1 = args[1].(interfaces.ListInvoicesByCardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceRepository_ListByCard_Call) Return(invoices []*entities.Invoice, err error) *InvoiceRepository_ListByCard_Call {
	_c.Call.Return(invoices, err)
	return _c
}

func (_c *InvoiceRepository_ListByCard_Call) RunAndReturn(run func(ctx context.Context, params interfaces.ListInvoicesByCardParams) ([]*entities.Invoice, error)) *InvoiceRepository_ListByCard_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserAndMonthPaginated provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) ListByUserAndMonthPaginated(ctx context.Context, params interfaces.ListInvoicesByMonthParams) ([]*entities.Invoice, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserAndMonthPaginated")
	}

	var r0 []*entities.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListInvoicesByMonthParams) ([]*entities.Invoice, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListInvoicesByMonthParams) []*entities.Invoice); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.ListInvoicesByMonthParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceRepository_ListByUserAndMonthPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserAndMonthPaginated'
type InvoiceRepository_ListByUserAndMonthPaginated_Call struct {
	*mock.Call
}

// ListByUserAndMonthPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - params interfaces.ListInvoicesByMonthParams
func (_e *InvoiceRepository_Expecter) ListByUserAndMonthPaginated(ctx interface{}, params interface{}) *InvoiceRepository_ListByUserAndMonthPaginated_Call {
	return &InvoiceRepository_ListByUserAndMonthPaginated_Call{Call: _e.mock.On("ListByUserAndMonthPaginated", ctx, params)}
}

func (_c *InvoiceRepository_ListByUserAndMonthPaginated_Call) Run(run func(ctx context.Context, params interfaces.ListInvoicesByMonthParams)) *InvoiceRepository_ListByUserAndMonthPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.ListInvoicesByMonthParams
		if args[1] != nil {
			arg1 = args[1].(interfaces.ListInvoicesByMonthParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceRepository_ListByUserAndMonthPaginated_Call) Return(invoices []*entities.Invoice, err error) *InvoiceRepository_ListByUserAndMonthPaginated_Call {
	_c.Call.Return(invoices, err)
	return _c
}

func (_c *InvoiceRepository_ListByUserAndMonthPaginated_Call) RunAndReturn(run func(ctx context.Context, params interfaces.ListInvoicesByMonthParams) ([]*entities.Invoice, error)) *InvoiceRepository_ListByUserAndMonthPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) Update(ctx context.Context, invoice *entities.Invoice) error {
	ret := _mock.Called(ctx, invoice)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Invoice) error); ok {
		r0 = returnFunc(ctx, invoice)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvoiceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type InvoiceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - invoice *entities.Invoice
func (_e *InvoiceRepository_Expecter) Update(ctx interface{}, invoice interface{}) *InvoiceRepository_Update_Call {
	return &InvoiceRepository_Update_Call{Call: _e.mock.On("Update", ctx, invoice)}
}

func (_c *InvoiceRepository_Update_Call) Run(run func(ctx context.Context, invoice *entities.Invoice)) *InvoiceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Invoice
		if args[1] != nil {
			arg1 = args[1].(*entities.Invoice)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceRepository_Update_Call) Return(err error) *InvoiceRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvoiceRepository_Update_Call) RunAndReturn(run func(ctx context.Context, invoice *entities.Invoice) error) *InvoiceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) UpdateItem(ctx context.Context, item *entities.InvoiceItem) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.InvoiceItem) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvoiceRepository_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type InvoiceRepository_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *entities.InvoiceItem
func (_e *InvoiceRepository_Expecter) UpdateItem(ctx interface{}, item interface{}) *InvoiceRepository_UpdateItem_Call {
	return &InvoiceRepository_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, item)}
}

func (_c *InvoiceRepository_UpdateItem_Call) Run(run func(ctx context.Context, item *entities.InvoiceItem)) *InvoiceRepository_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.InvoiceItem
		if args[1] != nil {
			arg1 = args[1].(*entities.InvoiceItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceRepository_UpdateItem_Call) Return(err error) *InvoiceRepository_UpdateItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvoiceRepository_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, item *entities.InvoiceItem) error) *InvoiceRepository_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertInvoice provides a mock function for the type InvoiceRepository
func (_mock *InvoiceRepository) UpsertInvoice(ctx context.Context, invoice *entities.Invoice) (*entities.Invoice, error) {
	ret := _mock.Called(ctx, invoice)

	if len(ret) == 0 {
		panic("no return value specified for UpsertInvoice")
	}

	var r0 *entities.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Invoice) (*entities.Invoice, error)); ok {
		return returnFunc(ctx, invoice)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Invoice) *entities.Invoice); ok {
		r0 = returnFunc(ctx, invoice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Invoice) error); ok {
		r1 = returnFunc(ctx, invoice)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceRepository_UpsertInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertInvoice'
type InvoiceRepository_UpsertInvoice_Call struct {
	*mock.Call
}

// UpsertInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - invoice *entities.Invoice
func (_e *InvoiceRepository_Expecter) UpsertInvoice(ctx interface{}, invoice interface{}) *InvoiceRepository_UpsertInvoice_Call {
	return &InvoiceRepository_UpsertInvoice_Call{Call: _e.mock.On("UpsertInvoice", ctx, invoice)}
}

func (_c *InvoiceRepository_UpsertInvoice_Call) Run(run func(ctx context.Context, invoice *entities.Invoice)) *InvoiceRepository_UpsertInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Invoice
		if args[1] != nil {
			arg1 = args[1].(*entities.Invoice)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceRepository_UpsertInvoice_Call) Return(invoice1 *entities.Invoice, err error) *InvoiceRepository_UpsertInvoice_Call {
	_c.Call.Return(invoice1, err)
	return _c
}

func (_c *InvoiceRepository_UpsertInvoice_Call) RunAndReturn(run func(ctx context.Context, invoice *entities.Invoice) (*entities.Invoice, error)) *InvoiceRepository_UpsertInvoice_Call {
	_c.Call.Return(run)
	return _c
}
