// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	"github.com/jailtonjunior94/financial/internal/card/domain/entities"
	"github.com/jailtonjunior94/financial/internal/card/domain/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewCardRepository creates a new instance of CardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardRepository {
	mock := &CardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CardRepository is an autogenerated mock type for the CardRepository type
type CardRepository struct {
	mock.Mock
}

type CardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CardRepository) EXPECT() *CardRepository_Expecter {
	return &CardRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type CardRepository
func (_mock *CardRepository) FindByID(ctx context.Context, userID vos.UUID, id vos.UUID) (*entities.Card, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID) (*entities.Card, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID) *entities.Card); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Card)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, vos.UUID) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type CardRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
//   - id vos.UUID
func (_e *CardRepository_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *CardRepository_FindByID_Call {
	return &CardRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *CardRepository_FindByID_Call) Run(run func(ctx context.Context, userID vos.UUID, id vos.UUID)) *CardRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		var arg2 vos.UUID
		if args[2] != nil {
			arg2 = args[2].(vos.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CardRepository_FindByID_Call) Return(card *entities.Card, err error) *CardRepository_FindByID_Call {
	_c.Call.Return(card, err)
	return _c
}

func (_c *CardRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, id vos.UUID) (*entities.Card, error)) *CardRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type CardRepository
func (_mock *CardRepository) List(ctx context.Context, userID vos.UUID) ([]*entities.Card, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) ([]*entities.Card, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) []*entities.Card); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Card)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CardRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
func (_e *CardRepository_Expecter) List(ctx interface{}, userID interface{}) *CardRepository_List_Call {
	return &CardRepository_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *CardRepository_List_Call) Run(run func(ctx context.Context, userID vos.UUID)) *CardRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CardRepository_List_Call) Return(cards []*entities.Card, err error) *CardRepository_List_Call {
	_c.Call.Return(cards, err)
	return _c
}

func (_c *CardRepository_List_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID) ([]*entities.Card, error)) *CardRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaginated provides a mock function for the type CardRepository
func (_mock *CardRepository) ListPaginated(ctx context.Context, params interfaces.ListCardsParams) ([]*entities.Card, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPaginated")
	}

	var r0 []*entities.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListCardsParams) ([]*entities.Card, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListCardsParams) []*entities.Card); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Card)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.ListCardsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardRepository_ListPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaginated'
type CardRepository_ListPaginated_Call struct {
	*mock.Call
}

// ListPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - params interfaces.ListCardsParams
func (_e *CardRepository_Expecter) ListPaginated(ctx interface{}, params interface{}) *CardRepository_ListPaginated_Call {
	return &CardRepository_ListPaginated_Call{Call: _e.mock.On("ListPaginated", ctx, params)}
}

func (_c *CardRepository_ListPaginated_Call) Run(run func(ctx context.Context, params interfaces.ListCardsParams)) *CardRepository_ListPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.ListCardsParams
		if args[1] != nil {
			arg1 = args[1].(interfaces.ListCardsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CardRepository_ListPaginated_Call) Return(cards []*entities.Card, err error) *CardRepository_ListPaginated_Call {
	_c.Call.Return(cards, err)
	return _c
}

func (_c *CardRepository_ListPaginated_Call) RunAndReturn(run func(ctx context.Context, params interfaces.ListCardsParams) ([]*entities.Card, error)) *CardRepository_ListPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type CardRepository
func (_mock *CardRepository) Save(ctx context.Context, card *entities.Card) error {
	ret := _mock.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Card) error); ok {
		r0 = returnFunc(ctx, card)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CardRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type CardRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - card *entities.Card
func (_e *CardRepository_Expecter) Save(ctx interface{}, card interface{}) *CardRepository_Save_Call {
	return &CardRepository_Save_Call{Call: _e.mock.On("Save", ctx, card)}
}

func (_c *CardRepository_Save_Call) Run(run func(ctx context.Context, card *entities.Card)) *CardRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Card
		if args[1] != nil {
			arg1 = args[1].(*entities.Card)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CardRepository_Save_Call) Return(err error) *CardRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CardRepository_Save_Call) RunAndReturn(run func(ctx context.Context, card *entities.Card) error) *CardRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type CardRepository
func (_mock *CardRepository) Update(ctx context.Context, card *entities.Card) error {
	ret := _mock.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Card) error); ok {
		r0 = returnFunc(ctx, card)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CardRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CardRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - card *entities.Card
func (_e *CardRepository_Expecter) Update(ctx interface{}, card interface{}) *CardRepository_Update_Call {
	return &CardRepository_Update_Call{Call: _e.mock.On("Update", ctx, card)}
}

func (_c *CardRepository_Update_Call) Run(run func(ctx context.Context, card *entities.Card)) *CardRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Card
		if args[1] != nil {
			arg1 = args[1].(*entities.Card)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CardRepository_Update_Call) Return(err error) *CardRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CardRepository_Update_Call) RunAndReturn(run func(ctx context.Context, card *entities.Card) error) *CardRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
