// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	mock "github.com/stretchr/testify/mock"
)

// NewInvoiceChecker creates a new instance of InvoiceChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvoiceChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvoiceChecker {
	mock := &InvoiceChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InvoiceChecker is an autogenerated mock type for the InvoiceChecker type
type InvoiceChecker struct {
	mock.Mock
}

type InvoiceChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *InvoiceChecker) EXPECT() *InvoiceChecker_Expecter {
	return &InvoiceChecker_Expecter{mock: &_m.Mock}
}

// HasOpenInvoices provides a mock function for the type InvoiceChecker
func (_mock *InvoiceChecker) HasOpenInvoices(ctx context.Context, cardID vos.UUID) (bool, error) {
	ret := _mock.Called(ctx, cardID)

	if len(ret) == 0 {
		panic("no return value specified for HasOpenInvoices")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) (bool, error)); ok {
		return returnFunc(ctx, cardID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) bool); ok {
		r0 = returnFunc(ctx, cardID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID) error); ok {
		r1 = returnFunc(ctx, cardID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InvoiceChecker_HasOpenInvoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasOpenInvoices'
type InvoiceChecker_HasOpenInvoices_Call struct {
	*mock.Call
}

// HasOpenInvoices is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID vos.UUID
func (_e *InvoiceChecker_Expecter) HasOpenInvoices(ctx interface{}, cardID interface{}) *InvoiceChecker_HasOpenInvoices_Call {
	return &InvoiceChecker_HasOpenInvoices_Call{Call: _e.mock.On("HasOpenInvoices", ctx, cardID)}
}

func (_c *InvoiceChecker_HasOpenInvoices_Call) Run(run func(ctx context.Context, cardID vos.UUID)) *InvoiceChecker_HasOpenInvoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvoiceChecker_HasOpenInvoices_Call) Return(b bool, err error) *InvoiceChecker_HasOpenInvoices_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *InvoiceChecker_HasOpenInvoices_Call) RunAndReturn(run func(ctx context.Context, cardID vos.UUID) (bool, error)) *InvoiceChecker_HasOpenInvoices_Call {
	_c.Call.Return(run)
	return _c
}
