// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	"github.com/jailtonjunior94/financial/internal/category/domain/entities"
	"github.com/jailtonjunior94/financial/internal/category/domain/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

type CategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryRepository) EXPECT() *CategoryRepository_Expecter {
	return &CategoryRepository_Expecter{mock: &_m.Mock}
}

// CheckCycleExists provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) CheckCycleExists(ctx context.Context, userID vos.UUID, categoryID vos.UUID, parentID vos.UUID) (bool, error) {
	ret := _mock.Called(ctx, userID, categoryID, parentID)

	if len(ret) == 0 {
		panic("no return value specified for CheckCycleExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID, vos.UUID) (bool, error)); ok {
		return returnFunc(ctx, userID, categoryID, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID, vos.UUID) bool); ok {
		r0 = returnFunc(ctx, userID, categoryID, parentID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, vos.UUID, vos.UUID) error); ok {
		r1 = returnFunc(ctx, userID, categoryID, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryRepository_CheckCycleExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckCycleExists'
type CategoryRepository_CheckCycleExists_Call struct {
	*mock.Call
}

// CheckCycleExists is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
//   - categoryID vos.UUID
//   - parentID vos.UUID
func (_e *CategoryRepository_Expecter) CheckCycleExists(ctx interface{}, userID interface{}, categoryID interface{}, parentID interface{}) *CategoryRepository_CheckCycleExists_Call {
	return &CategoryRepository_CheckCycleExists_Call{Call: _e.mock.On("CheckCycleExists", ctx, userID, categoryID, parentID)}
}

func (_c *CategoryRepository_CheckCycleExists_Call) Run(run func(ctx context.Context, userID vos.UUID, categoryID vos.UUID, parentID vos.UUID)) *CategoryRepository_CheckCycleExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		var arg2 vos.UUID
		if args[2] != nil {
			arg2 = args[2].(vos.UUID)
		}
		var arg3 vos.UUID
		if args[3] != nil {
			arg3 = args[3].(vos.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CategoryRepository_CheckCycleExists_Call) Return(b bool, err error) *CategoryRepository_CheckCycleExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *CategoryRepository_CheckCycleExists_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, categoryID vos.UUID, parentID vos.UUID) (bool, error)) *CategoryRepository_CheckCycleExists_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) FindByID(ctx context.Context, userID vos.UUID, id vos.UUID) (*entities.Category, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID) (*entities.Category, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID) *entities.Category); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, vos.UUID) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type CategoryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
//   - id vos.UUID
func (_e *CategoryRepository_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *CategoryRepository_FindByID_Call {
	return &CategoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *CategoryRepository_FindByID_Call) Run(run func(ctx context.Context, userID vos.UUID, id vos.UUID)) *CategoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		var arg2 vos.UUID
		if args[2] != nil {
			arg2 = args[2].(vos.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CategoryRepository_FindByID_Call) Return(category *entities.Category, err error) *CategoryRepository_FindByID_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *CategoryRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, id vos.UUID) (*entities.Category, error)) *CategoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) List(ctx context.Context, userID vos.UUID) ([]*entities.Category, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) ([]*entities.Category, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) []*entities.Category); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CategoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID vos.UUID
func (_e *CategoryRepository_Expecter) List(ctx interface{}, userID interface{}) *CategoryRepository_List_Call {
	return &CategoryRepository_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *CategoryRepository_List_Call) Run(run func(ctx context.Context, userID vos.UUID)) *CategoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vos.UUID
		if args[1] != nil {
			arg1 = args[1].(vos.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryRepository_List_Call) Return(categorys []*entities.Category, err error) *CategoryRepository_List_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *CategoryRepository_List_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID) ([]*entities.Category, error)) *CategoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaginated provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) ListPaginated(ctx context.Context, params interfaces.ListCategoriesParams) ([]*entities.Category, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPaginated")
	}

	var r0 []*entities.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListCategoriesParams) ([]*entities.Category, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListCategoriesParams) []*entities.Category); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.ListCategoriesParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryRepository_ListPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaginated'
type CategoryRepository_ListPaginated_Call struct {
	*mock.Call
}

// ListPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - params interfaces.ListCategoriesParams
func (_e *CategoryRepository_Expecter) ListPaginated(ctx interface{}, params interface{}) *CategoryRepository_ListPaginated_Call {
	return &CategoryRepository_ListPaginated_Call{Call: _e.mock.On("ListPaginated", ctx, params)}
}

func (_c *CategoryRepository_ListPaginated_Call) Run(run func(ctx context.Context, params interfaces.ListCategoriesParams)) *CategoryRepository_ListPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.ListCategoriesParams
		if args[1] != nil {
			arg1 = args[1].(interfaces.ListCategoriesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryRepository_ListPaginated_Call) Return(categorys []*entities.Category, err error) *CategoryRepository_ListPaginated_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *CategoryRepository_ListPaginated_Call) RunAndReturn(run func(ctx context.Context, params interfaces.ListCategoriesParams) ([]*entities.Category, error)) *CategoryRepository_ListPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) Save(ctx context.Context, category *entities.Category) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Category) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CategoryRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type CategoryRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - category *entities.Category
func (_e *CategoryRepository_Expecter) Save(ctx interface{}, category interface{}) *CategoryRepository_Save_Call {
	return &CategoryRepository_Save_Call{Call: _e.mock.On("Save", ctx, category)}
}

func (_c *CategoryRepository_Save_Call) Run(run func(ctx context.Context, category *entities.Category)) *CategoryRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Category
		if args[1] != nil {
			arg1 = args[1].(*entities.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryRepository_Save_Call) Return(err error) *CategoryRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CategoryRepository_Save_Call) RunAndReturn(run func(ctx context.Context, category *entities.Category) error) *CategoryRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) Update(ctx context.Context, category *entities.Category) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Category) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - category *entities.Category
func (_e *CategoryRepository_Expecter) Update(ctx interface{}, category interface{}) *CategoryRepository_Update_Call {
	return &CategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *CategoryRepository_Update_Call) Run(run func(ctx context.Context, category *entities.Category)) *CategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Category
		if args[1] != nil {
			arg1 = args[1].(*entities.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryRepository_Update_Call) Return(err error) *CategoryRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CategoryRepository_Update_Call) RunAndReturn(run func(ctx context.Context, category *entities.Category) error) *CategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
