// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
"context"

"github.com/JailtonJunior94/devkit-go/pkg/vos"
"github.com/jailtonjunior94/financial/internal/category/domain/entities"
"github.com/jailtonjunior94/financial/internal/category/domain/interfaces"
mock "github.com/stretchr/testify/mock"
)

// NewCategoryRepository creates a new instance of CategoryRepository.
func NewCategoryRepository(t interface {
mock.TestingT
Cleanup(func())
}) *CategoryRepository {
mock := &CategoryRepository{}
mock.Mock.Test(t)

t.Cleanup(func() { mock.AssertExpectations(t) })

return mock
}

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
mock.Mock
}

type CategoryRepository_Expecter struct {
mock *mock.Mock
}

func (_m *CategoryRepository) EXPECT() *CategoryRepository_Expecter {
return &CategoryRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) FindByID(ctx context.Context, userID vos.UUID, id vos.UUID) (*entities.Category, error) {
ret := _mock.Called(ctx, userID, id)

if len(ret) == 0 {
panic("no return value specified for FindByID")
}

var r0 *entities.Category
var r1 error
if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID) (*entities.Category, error)); ok {
return returnFunc(ctx, userID, id)
}
if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID) *entities.Category); ok {
r0 = returnFunc(ctx, userID, id)
} else {
if ret.Get(0) != nil {
r0 = ret.Get(0).(*entities.Category)
}
}
if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, vos.UUID) error); ok {
r1 = returnFunc(ctx, userID, id)
} else {
r1 = ret.Error(1)
}
return r0, r1
}

type CategoryRepository_FindByID_Call struct {
*mock.Call
}

func (_e *CategoryRepository_Expecter) FindByID(ctx interface{}, userID interface{}, id interface{}) *CategoryRepository_FindByID_Call {
return &CategoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, id)}
}

func (_c *CategoryRepository_FindByID_Call) Run(run func(ctx context.Context, userID vos.UUID, id vos.UUID)) *CategoryRepository_FindByID_Call {
_c.Call.Run(func(args mock.Arguments) {
run(args[0].(context.Context), args[1].(vos.UUID), args[2].(vos.UUID))
})
return _c
}

func (_c *CategoryRepository_FindByID_Call) Return(category *entities.Category, err error) *CategoryRepository_FindByID_Call {
_c.Call.Return(category, err)
return _c
}

func (_c *CategoryRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, id vos.UUID) (*entities.Category, error)) *CategoryRepository_FindByID_Call {
_c.Call.Return(run)
return _c
}

// ListPaginated provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) ListPaginated(ctx context.Context, params interfaces.ListCategoriesParams) ([]*entities.Category, error) {
ret := _mock.Called(ctx, params)

if len(ret) == 0 {
panic("no return value specified for ListPaginated")
}

var r0 []*entities.Category
var r1 error
if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListCategoriesParams) ([]*entities.Category, error)); ok {
return returnFunc(ctx, params)
}
if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListCategoriesParams) []*entities.Category); ok {
r0 = returnFunc(ctx, params)
} else {
if ret.Get(0) != nil {
r0 = ret.Get(0).([]*entities.Category)
}
}
if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.ListCategoriesParams) error); ok {
r1 = returnFunc(ctx, params)
} else {
r1 = ret.Error(1)
}
return r0, r1
}

type CategoryRepository_ListPaginated_Call struct {
*mock.Call
}

func (_e *CategoryRepository_Expecter) ListPaginated(ctx interface{}, params interface{}) *CategoryRepository_ListPaginated_Call {
return &CategoryRepository_ListPaginated_Call{Call: _e.mock.On("ListPaginated", ctx, params)}
}

func (_c *CategoryRepository_ListPaginated_Call) Run(run func(ctx context.Context, params interfaces.ListCategoriesParams)) *CategoryRepository_ListPaginated_Call {
_c.Call.Run(func(args mock.Arguments) {
run(args[0].(context.Context), args[1].(interfaces.ListCategoriesParams))
})
return _c
}

func (_c *CategoryRepository_ListPaginated_Call) Return(categorys []*entities.Category, err error) *CategoryRepository_ListPaginated_Call {
_c.Call.Return(categorys, err)
return _c
}

func (_c *CategoryRepository_ListPaginated_Call) RunAndReturn(run func(ctx context.Context, params interfaces.ListCategoriesParams) ([]*entities.Category, error)) *CategoryRepository_ListPaginated_Call {
_c.Call.Return(run)
return _c
}

// Save provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) Save(ctx context.Context, category *entities.Category) error {
ret := _mock.Called(ctx, category)

if len(ret) == 0 {
panic("no return value specified for Save")
}

var r0 error
if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Category) error); ok {
r0 = returnFunc(ctx, category)
} else {
r0 = ret.Error(0)
}
return r0
}

type CategoryRepository_Save_Call struct {
*mock.Call
}

func (_e *CategoryRepository_Expecter) Save(ctx interface{}, category interface{}) *CategoryRepository_Save_Call {
return &CategoryRepository_Save_Call{Call: _e.mock.On("Save", ctx, category)}
}

func (_c *CategoryRepository_Save_Call) Run(run func(ctx context.Context, category *entities.Category)) *CategoryRepository_Save_Call {
_c.Call.Run(func(args mock.Arguments) {
run(args[0].(context.Context), args[1].(*entities.Category))
})
return _c
}

func (_c *CategoryRepository_Save_Call) Return(err error) *CategoryRepository_Save_Call {
_c.Call.Return(err)
return _c
}

func (_c *CategoryRepository_Save_Call) RunAndReturn(run func(ctx context.Context, category *entities.Category) error) *CategoryRepository_Save_Call {
_c.Call.Return(run)
return _c
}

// Update provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) Update(ctx context.Context, category *entities.Category) error {
ret := _mock.Called(ctx, category)

if len(ret) == 0 {
panic("no return value specified for Update")
}

var r0 error
if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Category) error); ok {
r0 = returnFunc(ctx, category)
} else {
r0 = ret.Error(0)
}
return r0
}

type CategoryRepository_Update_Call struct {
*mock.Call
}

func (_e *CategoryRepository_Expecter) Update(ctx interface{}, category interface{}) *CategoryRepository_Update_Call {
return &CategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *CategoryRepository_Update_Call) Run(run func(ctx context.Context, category *entities.Category)) *CategoryRepository_Update_Call {
_c.Call.Run(func(args mock.Arguments) {
run(args[0].(context.Context), args[1].(*entities.Category))
})
return _c
}

func (_c *CategoryRepository_Update_Call) Return(err error) *CategoryRepository_Update_Call {
_c.Call.Return(err)
return _c
}

func (_c *CategoryRepository_Update_Call) RunAndReturn(run func(ctx context.Context, category *entities.Category) error) *CategoryRepository_Update_Call {
_c.Call.Return(run)
return _c
}

// SoftDelete provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) SoftDelete(ctx context.Context, id vos.UUID) error {
ret := _mock.Called(ctx, id)

if len(ret) == 0 {
panic("no return value specified for SoftDelete")
}

var r0 error
if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) error); ok {
r0 = returnFunc(ctx, id)
} else {
r0 = ret.Error(0)
}
return r0
}

type CategoryRepository_SoftDelete_Call struct {
*mock.Call
}

func (_e *CategoryRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *CategoryRepository_SoftDelete_Call {
return &CategoryRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *CategoryRepository_SoftDelete_Call) Run(run func(ctx context.Context, id vos.UUID)) *CategoryRepository_SoftDelete_Call {
_c.Call.Run(func(args mock.Arguments) {
run(args[0].(context.Context), args[1].(vos.UUID))
})
return _c
}

func (_c *CategoryRepository_SoftDelete_Call) Return(err error) *CategoryRepository_SoftDelete_Call {
_c.Call.Return(err)
return _c
}

func (_c *CategoryRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, id vos.UUID) error) *CategoryRepository_SoftDelete_Call {
_c.Call.Return(run)
return _c
}
