// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoryMock

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/vos"
	"github.com/jailtonjunior94/financial/internal/category/domain/entities"
	"github.com/jailtonjunior94/financial/internal/category/domain/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewSubcategoryRepository creates a new instance of SubcategoryRepository.
func NewSubcategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubcategoryRepository {
	mock := &SubcategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubcategoryRepository is an autogenerated mock type for the SubcategoryRepository type
type SubcategoryRepository struct {
	mock.Mock
}

type SubcategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SubcategoryRepository) EXPECT() *SubcategoryRepository_Expecter {
	return &SubcategoryRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type SubcategoryRepository
func (_mock *SubcategoryRepository) FindByID(ctx context.Context, userID vos.UUID, categoryID vos.UUID, id vos.UUID) (*entities.Subcategory, error) {
	ret := _mock.Called(ctx, userID, categoryID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Subcategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID, vos.UUID) (*entities.Subcategory, error)); ok {
		return returnFunc(ctx, userID, categoryID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID, vos.UUID, vos.UUID) *entities.Subcategory); ok {
		r0 = returnFunc(ctx, userID, categoryID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Subcategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID, vos.UUID, vos.UUID) error); ok {
		r1 = returnFunc(ctx, userID, categoryID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type SubcategoryRepository_FindByID_Call struct {
	*mock.Call
}

func (_e *SubcategoryRepository_Expecter) FindByID(ctx interface{}, userID interface{}, categoryID interface{}, id interface{}) *SubcategoryRepository_FindByID_Call {
	return &SubcategoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, categoryID, id)}
}

func (_c *SubcategoryRepository_FindByID_Call) Run(run func(ctx context.Context, userID vos.UUID, categoryID vos.UUID, id vos.UUID)) *SubcategoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vos.UUID), args[2].(vos.UUID), args[3].(vos.UUID))
	})
	return _c
}

func (_c *SubcategoryRepository_FindByID_Call) Return(subcategory *entities.Subcategory, err error) *SubcategoryRepository_FindByID_Call {
	_c.Call.Return(subcategory, err)
	return _c
}

func (_c *SubcategoryRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, userID vos.UUID, categoryID vos.UUID, id vos.UUID) (*entities.Subcategory, error)) *SubcategoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCategoryID provides a mock function for the type SubcategoryRepository
func (_mock *SubcategoryRepository) FindByCategoryID(ctx context.Context, categoryID vos.UUID) ([]*entities.Subcategory, error) {
	ret := _mock.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCategoryID")
	}

	var r0 []*entities.Subcategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) ([]*entities.Subcategory, error)); ok {
		return returnFunc(ctx, categoryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) []*entities.Subcategory); ok {
		r0 = returnFunc(ctx, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Subcategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vos.UUID) error); ok {
		r1 = returnFunc(ctx, categoryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type SubcategoryRepository_FindByCategoryID_Call struct {
	*mock.Call
}

func (_e *SubcategoryRepository_Expecter) FindByCategoryID(ctx interface{}, categoryID interface{}) *SubcategoryRepository_FindByCategoryID_Call {
	return &SubcategoryRepository_FindByCategoryID_Call{Call: _e.mock.On("FindByCategoryID", ctx, categoryID)}
}

func (_c *SubcategoryRepository_FindByCategoryID_Call) Run(run func(ctx context.Context, categoryID vos.UUID)) *SubcategoryRepository_FindByCategoryID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vos.UUID))
	})
	return _c
}

func (_c *SubcategoryRepository_FindByCategoryID_Call) Return(subcategorys []*entities.Subcategory, err error) *SubcategoryRepository_FindByCategoryID_Call {
	_c.Call.Return(subcategorys, err)
	return _c
}

func (_c *SubcategoryRepository_FindByCategoryID_Call) RunAndReturn(run func(ctx context.Context, categoryID vos.UUID) ([]*entities.Subcategory, error)) *SubcategoryRepository_FindByCategoryID_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaginated provides a mock function for the type SubcategoryRepository
func (_mock *SubcategoryRepository) ListPaginated(ctx context.Context, params interfaces.ListSubcategoriesParams) ([]*entities.Subcategory, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPaginated")
	}

	var r0 []*entities.Subcategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListSubcategoriesParams) ([]*entities.Subcategory, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.ListSubcategoriesParams) []*entities.Subcategory); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Subcategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.ListSubcategoriesParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type SubcategoryRepository_ListPaginated_Call struct {
	*mock.Call
}

func (_e *SubcategoryRepository_Expecter) ListPaginated(ctx interface{}, params interface{}) *SubcategoryRepository_ListPaginated_Call {
	return &SubcategoryRepository_ListPaginated_Call{Call: _e.mock.On("ListPaginated", ctx, params)}
}

func (_c *SubcategoryRepository_ListPaginated_Call) Run(run func(ctx context.Context, params interfaces.ListSubcategoriesParams)) *SubcategoryRepository_ListPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.ListSubcategoriesParams))
	})
	return _c
}

func (_c *SubcategoryRepository_ListPaginated_Call) Return(subcategorys []*entities.Subcategory, err error) *SubcategoryRepository_ListPaginated_Call {
	_c.Call.Return(subcategorys, err)
	return _c
}

func (_c *SubcategoryRepository_ListPaginated_Call) RunAndReturn(run func(ctx context.Context, params interfaces.ListSubcategoriesParams) ([]*entities.Subcategory, error)) *SubcategoryRepository_ListPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type SubcategoryRepository
func (_mock *SubcategoryRepository) Save(ctx context.Context, subcategory *entities.Subcategory) error {
	ret := _mock.Called(ctx, subcategory)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Subcategory) error); ok {
		r0 = returnFunc(ctx, subcategory)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type SubcategoryRepository_Save_Call struct {
	*mock.Call
}

func (_e *SubcategoryRepository_Expecter) Save(ctx interface{}, subcategory interface{}) *SubcategoryRepository_Save_Call {
	return &SubcategoryRepository_Save_Call{Call: _e.mock.On("Save", ctx, subcategory)}
}

func (_c *SubcategoryRepository_Save_Call) Run(run func(ctx context.Context, subcategory *entities.Subcategory)) *SubcategoryRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Subcategory))
	})
	return _c
}

func (_c *SubcategoryRepository_Save_Call) Return(err error) *SubcategoryRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubcategoryRepository_Save_Call) RunAndReturn(run func(ctx context.Context, subcategory *entities.Subcategory) error) *SubcategoryRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type SubcategoryRepository
func (_mock *SubcategoryRepository) Update(ctx context.Context, subcategory *entities.Subcategory) error {
	ret := _mock.Called(ctx, subcategory)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Subcategory) error); ok {
		r0 = returnFunc(ctx, subcategory)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type SubcategoryRepository_Update_Call struct {
	*mock.Call
}

func (_e *SubcategoryRepository_Expecter) Update(ctx interface{}, subcategory interface{}) *SubcategoryRepository_Update_Call {
	return &SubcategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, subcategory)}
}

func (_c *SubcategoryRepository_Update_Call) Run(run func(ctx context.Context, subcategory *entities.Subcategory)) *SubcategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Subcategory))
	})
	return _c
}

func (_c *SubcategoryRepository_Update_Call) Return(err error) *SubcategoryRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubcategoryRepository_Update_Call) RunAndReturn(run func(ctx context.Context, subcategory *entities.Subcategory) error) *SubcategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type SubcategoryRepository
func (_mock *SubcategoryRepository) SoftDelete(ctx context.Context, id vos.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type SubcategoryRepository_SoftDelete_Call struct {
	*mock.Call
}

func (_e *SubcategoryRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *SubcategoryRepository_SoftDelete_Call {
	return &SubcategoryRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *SubcategoryRepository_SoftDelete_Call) Run(run func(ctx context.Context, id vos.UUID)) *SubcategoryRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vos.UUID))
	})
	return _c
}

func (_c *SubcategoryRepository_SoftDelete_Call) Return(err error) *SubcategoryRepository_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubcategoryRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, id vos.UUID) error) *SubcategoryRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteByCategoryID provides a mock function for the type SubcategoryRepository
func (_mock *SubcategoryRepository) SoftDeleteByCategoryID(ctx context.Context, categoryID vos.UUID) error {
	ret := _mock.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByCategoryID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vos.UUID) error); ok {
		r0 = returnFunc(ctx, categoryID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type SubcategoryRepository_SoftDeleteByCategoryID_Call struct {
	*mock.Call
}

func (_e *SubcategoryRepository_Expecter) SoftDeleteByCategoryID(ctx interface{}, categoryID interface{}) *SubcategoryRepository_SoftDeleteByCategoryID_Call {
	return &SubcategoryRepository_SoftDeleteByCategoryID_Call{Call: _e.mock.On("SoftDeleteByCategoryID", ctx, categoryID)}
}

func (_c *SubcategoryRepository_SoftDeleteByCategoryID_Call) Run(run func(ctx context.Context, categoryID vos.UUID)) *SubcategoryRepository_SoftDeleteByCategoryID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vos.UUID))
	})
	return _c
}

func (_c *SubcategoryRepository_SoftDeleteByCategoryID_Call) Return(err error) *SubcategoryRepository_SoftDeleteByCategoryID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubcategoryRepository_SoftDeleteByCategoryID_Call) RunAndReturn(run func(ctx context.Context, categoryID vos.UUID) error) *SubcategoryRepository_SoftDeleteByCategoryID_Call {
	_c.Call.Return(run)
	return _c
}
