// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewErrorHandler creates a new instance of ErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorHandler {
	mock := &ErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ErrorHandler is an autogenerated mock type for the ErrorHandler type
type ErrorHandler struct {
	mock.Mock
}

type ErrorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorHandler) EXPECT() *ErrorHandler_Expecter {
	return &ErrorHandler_Expecter{mock: &_m.Mock}
}

// HandleError provides a mock function for the type ErrorHandler
func (_mock *ErrorHandler) HandleError(w http.ResponseWriter, r *http.Request, err error) {
	_mock.Called(w, r, err)
	return
}

// ErrorHandler_HandleError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleError'
type ErrorHandler_HandleError_Call struct {
	*mock.Call
}

// HandleError is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - err error
func (_e *ErrorHandler_Expecter) HandleError(w interface{}, r interface{}, err interface{}) *ErrorHandler_HandleError_Call {
	return &ErrorHandler_HandleError_Call{Call: _e.mock.On("HandleError", w, r, err)}
}

func (_c *ErrorHandler_HandleError_Call) Run(run func(w http.ResponseWriter, r *http.Request, err error)) *ErrorHandler_HandleError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ErrorHandler_HandleError_Call) Return() *ErrorHandler_HandleError_Call {
	_c.Call.Return()
	return _c
}

func (_c *ErrorHandler_HandleError_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, err error)) *ErrorHandler_HandleError_Call {
	_c.Run(run)
	return _c
}
